"""
gen_sym_tables.py
Generates src/backends/sym_tables/ symbol lookup tables for fb_auto_populate_ext_ops().

For each backend family, produces a .c file with a flat array of
  { op_id, "symbol_name" }
entries that can be passed to fb_auto_populate_ext_ops() at backend init.

Tables generated:
  lapacke_sym_table.c   - LAPACKE_* symbols (OpenBLAS + MKL, IDs 157-1321)
  cblas_ext_sym_table.c - cblas_* extended batch symbols (IDs 1634-1807)
  mkl_ext_sym_table.c   - mkl_* extension symbols (IDs 1808-1850)
  scalapack_sym_table.c - p*_ Fortran symbols (IDs 1322-1633)
  cublas_sym_table.c    - cublas* / cusolverDn* symbol names (IDs 0-1321)
  rocblas_sym_table.c   - rocblas_* / rocsolver_* symbol names (IDs 0-1321)

Run from the faster-blaster workspace root:
  python gen_sym_tables.py
"""

import re, os

# ── Paths (relative to workspace root where this script lives) ───────────────
OPS_HEADER = "src/judge/judge_op_ids.h"
OUT_DIR    = "src/backends/sym_tables"

# ── Parse all FB_OP_* defs (skip sentinel _BEGIN/_END lines) ─────────────────
ops = []
for line in open(OPS_HEADER, encoding="utf-8"):
    m = re.match(r"#define (FB_OP_([A-Z0-9_]+))\s+(\d+)", line.strip())
    if m and not m.group(2).startswith("_"):
        ops.append((m.group(2).lower(), m.group(1), int(m.group(3))))
ops.sort(key=lambda x: x[2])

os.makedirs(OUT_DIR, exist_ok=True)

AUTOGEN_NOTICE = (
    "/* AUTO-GENERATED by gen_sym_tables.py — do not edit by hand.\n"
    " * Re-run from workspace root:  python gen_sym_tables.py\n"
    " */\n"
)

# Each .c file lives in  src/backends/sym_tables/
# From there, the relative paths to other headers are:
#   ../backend_auto_detect.h      (sym_tables.h itself)
#   ../../judge/judge_op_ids.h
C_INCLUDES = (
    '#include "sym_tables.h"         /* fb_sym_entry_t, extern decls */\n'
    '#include "../../judge/judge_op_ids.h"  /* FB_OP_* macros       */\n'
    "\n"
)


def write_table(filename, varname, entries, comment):
    """Write one symbol table .c file."""
    path = os.path.join(OUT_DIR, filename)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(AUTOGEN_NOTICE)
        f.write(f"/* {comment} */\n\n")
        f.write(C_INCLUDES)
        f.write(f"const fb_sym_entry_t {varname}[] = {{\n")
        for (macro, sym) in entries:
            f.write(f'    {{ {macro:<48s} "{sym}" }},\n')
        f.write("};\n\n")
        # Use sizeof so count stays correct if anyone manually adds entries.
        f.write(
            f"const size_t {varname}_count =\n"
            f"    sizeof({varname}) / sizeof({varname}[0]);\n"
        )
    print(f"  {path}  ({len(entries)} entries)")


# ─────────────────────────────────────────────────────────────────────────────
# 1.  LAPACKE symbol table  (IDs 157 – 1321, inclusive)
#     Symbol = "LAPACKE_" + lowercase_op_name
#     Compatible backends: OpenBLAS (with LAPACKE), Intel MKL, AOCL-LAPACK
# ─────────────────────────────────────────────────────────────────────────────
lapacke = [
    (macro, f"LAPACKE_{name}")
    for name, macro, op_id in ops
    if 157 <= op_id <= 1321
]
write_table(
    "lapacke_sym_table.c", "k_lapacke_symbols", lapacke,
    "LAPACKE_* symbols — OpenBLAS / MKL / AOCL-LAPACK  (IDs 157-1321)"
)

# ─────────────────────────────────────────────────────────────────────────────
# 2.  Extended BLAS / cblas_batch symbols  (IDs 1634 – 1807, inclusive)
#     Op names that already start with "cblas_" are used verbatim.
#     Others (saxpby, saxpy_batch, …) are prefixed with "cblas_".
# ─────────────────────────────────────────────────────────────────────────────
cblas_ext = []
for name, macro, op_id in ops:
    if 1634 <= op_id <= 1807:
        sym = name if name.startswith("cblas_") else f"cblas_{name}"
        cblas_ext.append((macro, sym))
write_table(
    "cblas_ext_sym_table.c", "k_cblas_ext_symbols", cblas_ext,
    "cblas_* extended/batch symbols — Intel MKL CBLAS extensions  (IDs 1634-1807)"
)

# ─────────────────────────────────────────────────────────────────────────────
# 3.  MKL extension symbols  (IDs 1808 – 1850, inclusive)
#     Op names already start with "mkl_" — symbol = op_name verbatim.
# ─────────────────────────────────────────────────────────────────────────────
mkl_ext = [
    (macro, name)
    for name, macro, op_id in ops
    if 1808 <= op_id <= 1850
]
write_table(
    "mkl_ext_sym_table.c", "k_mkl_ext_symbols", mkl_ext,
    "mkl_* extension symbols — Intel MKL specific  (IDs 1808-1850)"
)

# ─────────────────────────────────────────────────────────────────────────────
# 4.  ScaLAPACK Fortran symbols  (IDs 1322 – 1633, inclusive)
#     Fortran convention: symbol = op_name + "_"  (e.g. "psgesv_")
#     NOTE: callers via ext_ops must use Fortran pass-by-reference convention.
# ─────────────────────────────────────────────────────────────────────────────
scalapack = [
    (macro, f"{name}_")
    for name, macro, op_id in ops
    if 1322 <= op_id <= 1633
]
write_table(
    "scalapack_sym_table.c", "k_scalapack_symbols", scalapack,
    "ScaLAPACK Fortran p*_ symbols — MPI-based routines  (IDs 1322-1633)"
)

# ─────────────────────────────────────────────────────────────────────────────
# 5.  cuBLAS / cuSolver symbol names  (IDs 0 – 1321, inclusive)
#     BLAS ops  → "cublas{PREC}{rest}"      e.g. sgemm  → "cublasSgemm"
#     LAPACK ops → "cusolverDn{PREC}{rest}" e.g. sgetrf → "cusolverDnSgetrf"
#     Only S/D/C/Z-prefixed ops are emitted (others have no standard mapping).
# ─────────────────────────────────────────────────────────────────────────────
_PREC = {'s': 'S', 'd': 'D', 'c': 'C', 'z': 'Z'}

def _cublas_sym(name, op_id):
    p = _PREC.get(name[0]) if name else None
    if not p:
        return None
    rest = name[1:]
    if 0 <= op_id <= 156:
        return f"cublas{p}{rest}"
    if 157 <= op_id <= 1321:
        return f"cusolverDn{p}{rest}"
    return None

cublas_entries = [
    (macro, sym)
    for name, macro, op_id in ops
    if (sym := _cublas_sym(name, op_id)) is not None
]
write_table(
    "cublas_sym_table.c", "k_cublas_symbols", cublas_entries,
    "cuBLAS / cuSolver symbol names — NVIDIA GPU backend  (IDs 0-1321)"
)

# ─────────────────────────────────────────────────────────────────────────────
# 6.  rocBLAS / rocSOLVER symbol names  (IDs 0 – 1321, inclusive)
#     BLAS ops  → "rocblas_{op_name}"
#     LAPACK ops → "rocsolver_{op_name}"
# ─────────────────────────────────────────────────────────────────────────────
def _rocblas_sym(name, op_id):
    if 0 <= op_id <= 156:
        return f"rocblas_{name}"
    if 157 <= op_id <= 1321:
        return f"rocsolver_{name}"
    return None

rocblas_entries = [
    (macro, sym)
    for name, macro, op_id in ops
    if (sym := _rocblas_sym(name, op_id)) is not None
]
write_table(
    "rocblas_sym_table.c", "k_rocblas_symbols", rocblas_entries,
    "rocBLAS / rocSOLVER symbol names — AMD GPU backend  (IDs 0-1321)"
)

# ─────────────────────────────────────────────────────────────────────────────
# 7.  Write shared header  sym_tables.h
#     Lives alongside the .c files in src/backends/sym_tables/
#     Relative include path to backend_auto_detect.h: ../backend_auto_detect.h
# ─────────────────────────────────────────────────────────────────────────────
hdr_path = os.path.join(OUT_DIR, "sym_tables.h")
with open(hdr_path, "w", encoding="utf-8", newline="\n") as f:
    f.write(AUTOGEN_NOTICE)
    f.write("""
#ifndef FB_SYM_TABLES_H
#define FB_SYM_TABLES_H

/* fb_sym_entry_t is defined in the parent directory */
#include "../backend_auto_detect.h"

#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ── LAPACKE_* — OpenBLAS / MKL / AOCL-LAPACK  (IDs 157-1321) ─────────── */
extern const fb_sym_entry_t k_lapacke_symbols[];
extern const size_t         k_lapacke_symbols_count;

/* ── cblas_* extended/batch — MKL extensions  (IDs 1634-1807) ──────────── */
extern const fb_sym_entry_t k_cblas_ext_symbols[];
extern const size_t         k_cblas_ext_symbols_count;

/* ── mkl_* extensions — Intel MKL specific  (IDs 1808-1850) ────────────── */
extern const fb_sym_entry_t k_mkl_ext_symbols[];
extern const size_t         k_mkl_ext_symbols_count;

/* ── ScaLAPACK Fortran p*_ symbols  (IDs 1322-1633) ────────────────────── */
extern const fb_sym_entry_t k_scalapack_symbols[];
extern const size_t         k_scalapack_symbols_count;

/* ── cuBLAS / cuSolver symbol names  (IDs 0-1321) ──────────────────────── */
extern const fb_sym_entry_t k_cublas_symbols[];
extern const size_t         k_cublas_symbols_count;

/* ── rocBLAS / rocSOLVER symbol names  (IDs 0-1321) ────────────────────── */
extern const fb_sym_entry_t k_rocblas_symbols[];
extern const size_t         k_rocblas_symbols_count;

#ifdef __cplusplus
}
#endif

#endif /* FB_SYM_TABLES_H */
""")
print(f"  {hdr_path}")

print("\nDone — all sym tables written.")
