/* AUTO-GENERATED by gen_sym_tables.py — do not edit by hand.
 * Re-run from workspace root:  python gen_sym_tables.py
 */
/* mkl_* extension symbols — Intel MKL specific  (IDs 1808-1850) */

#include "sym_tables.h"         /* fb_sym_entry_t, extern decls */
#include "../../judge/judge_op_ids.h"  /* FB_OP_* macros       */

const fb_sym_entry_t k_mkl_ext_symbols[] = {
    { FB_OP_MKL_CIMATCOPY                             , FB_CONV_CBLAS   , "mkl_cimatcopy" },
    { FB_OP_MKL_CIMATCOPY_BATCH                       , FB_CONV_CBLAS   , "mkl_cimatcopy_batch" },
    { FB_OP_MKL_CIMATCOPY_BATCH_STRIDED               , FB_CONV_CBLAS   , "mkl_cimatcopy_batch_strided" },
    { FB_OP_MKL_COMATADD                              , FB_CONV_CBLAS   , "mkl_comatadd" },
    { FB_OP_MKL_COMATCOPY                             , FB_CONV_CBLAS   , "mkl_comatcopy" },
    { FB_OP_MKL_COMATCOPY2                            , FB_CONV_CBLAS   , "mkl_comatcopy2" },
    { FB_OP_MKL_COMATCOPY_BATCH                       , FB_CONV_CBLAS   , "mkl_comatcopy_batch" },
    { FB_OP_MKL_COMATCOPY_BATCH_STRIDED               , FB_CONV_CBLAS   , "mkl_comatcopy_batch_strided" },
    { FB_OP_MKL_DIMATCOPY                             , FB_CONV_CBLAS   , "mkl_dimatcopy" },
    { FB_OP_MKL_DIMATCOPY_BATCH                       , FB_CONV_CBLAS   , "mkl_dimatcopy_batch" },
    { FB_OP_MKL_DIMATCOPY_BATCH_STRIDED               , FB_CONV_CBLAS   , "mkl_dimatcopy_batch_strided" },
    { FB_OP_MKL_DOMATADD                              , FB_CONV_CBLAS   , "mkl_domatadd" },
    { FB_OP_MKL_DOMATCOPY                             , FB_CONV_CBLAS   , "mkl_domatcopy" },
    { FB_OP_MKL_DOMATCOPY2                            , FB_CONV_CBLAS   , "mkl_domatcopy2" },
    { FB_OP_MKL_DOMATCOPY_BATCH                       , FB_CONV_CBLAS   , "mkl_domatcopy_batch" },
    { FB_OP_MKL_DOMATCOPY_BATCH_STRIDED               , FB_CONV_CBLAS   , "mkl_domatcopy_batch_strided" },
    { FB_OP_MKL_JIT_CREATE_CGEMM                      , FB_CONV_CBLAS   , "mkl_jit_create_cgemm" },
    { FB_OP_MKL_JIT_CREATE_DGEMM                      , FB_CONV_CBLAS   , "mkl_jit_create_dgemm" },
    { FB_OP_MKL_JIT_CREATE_SGEMM                      , FB_CONV_CBLAS   , "mkl_jit_create_sgemm" },
    { FB_OP_MKL_JIT_CREATE_ZGEMM                      , FB_CONV_CBLAS   , "mkl_jit_create_zgemm" },
    { FB_OP_MKL_JIT_DESTROY                           , FB_CONV_CBLAS   , "mkl_jit_destroy" },
    { FB_OP_MKL_JIT_GET_CGEMM_PTR                     , FB_CONV_CBLAS   , "mkl_jit_get_cgemm_ptr" },
    { FB_OP_MKL_JIT_GET_DGEMM_PTR                     , FB_CONV_CBLAS   , "mkl_jit_get_dgemm_ptr" },
    { FB_OP_MKL_JIT_GET_SGEMM_PTR                     , FB_CONV_CBLAS   , "mkl_jit_get_sgemm_ptr" },
    { FB_OP_MKL_JIT_GET_ZGEMM_PTR                     , FB_CONV_CBLAS   , "mkl_jit_get_zgemm_ptr" },
    { FB_OP_MKL_SIMATCOPY                             , FB_CONV_CBLAS   , "mkl_simatcopy" },
    { FB_OP_MKL_SIMATCOPY_BATCH                       , FB_CONV_CBLAS   , "mkl_simatcopy_batch" },
    { FB_OP_MKL_SIMATCOPY_BATCH_STRIDED               , FB_CONV_CBLAS   , "mkl_simatcopy_batch_strided" },
    { FB_OP_MKL_SOMATADD                              , FB_CONV_CBLAS   , "mkl_somatadd" },
    { FB_OP_MKL_SOMATCOPY                             , FB_CONV_CBLAS   , "mkl_somatcopy" },
    { FB_OP_MKL_SOMATCOPY2                            , FB_CONV_CBLAS   , "mkl_somatcopy2" },
    { FB_OP_MKL_SOMATCOPY_BATCH                       , FB_CONV_CBLAS   , "mkl_somatcopy_batch" },
    { FB_OP_MKL_SOMATCOPY_BATCH_STRIDED               , FB_CONV_CBLAS   , "mkl_somatcopy_batch_strided" },
    { FB_OP_MKL_SPARSE_S_CREATE_CSR                   , FB_CONV_CBLAS   , "mkl_sparse_s_create_csr" },
    { FB_OP_MKL_SPARSE_S_MV                           , FB_CONV_CBLAS   , "mkl_sparse_s_mv" },
    { FB_OP_MKL_ZIMATCOPY                             , FB_CONV_CBLAS   , "mkl_zimatcopy" },
    { FB_OP_MKL_ZIMATCOPY_BATCH                       , FB_CONV_CBLAS   , "mkl_zimatcopy_batch" },
    { FB_OP_MKL_ZIMATCOPY_BATCH_STRIDED               , FB_CONV_CBLAS   , "mkl_zimatcopy_batch_strided" },
    { FB_OP_MKL_ZOMATADD                              , FB_CONV_CBLAS   , "mkl_zomatadd" },
    { FB_OP_MKL_ZOMATCOPY                             , FB_CONV_CBLAS   , "mkl_zomatcopy" },
    { FB_OP_MKL_ZOMATCOPY2                            , FB_CONV_CBLAS   , "mkl_zomatcopy2" },
    { FB_OP_MKL_ZOMATCOPY_BATCH                       , FB_CONV_CBLAS   , "mkl_zomatcopy_batch" },
    { FB_OP_MKL_ZOMATCOPY_BATCH_STRIDED               , FB_CONV_CBLAS   , "mkl_zomatcopy_batch_strided" },
};

const size_t k_mkl_ext_symbols_count =
    sizeof(k_mkl_ext_symbols) / sizeof(k_mkl_ext_symbols[0]);
