/* AUTO-GENERATED by gen_sym_tables.py — do not edit by hand.
 * Re-run from workspace root:  python gen_sym_tables.py
 */
/* mkl_* extension symbols — Intel MKL specific  (IDs 1808-1850) */

#include "sym_tables.h"         /* fb_sym_entry_t, extern decls */
#include "../../judge/judge_op_ids.h"  /* FB_OP_* macros       */

const fb_sym_entry_t k_mkl_ext_symbols[] = {
    { FB_OP_MKL_CIMATCOPY                              "mkl_cimatcopy" },
    { FB_OP_MKL_CIMATCOPY_BATCH                        "mkl_cimatcopy_batch" },
    { FB_OP_MKL_CIMATCOPY_BATCH_STRIDED                "mkl_cimatcopy_batch_strided" },
    { FB_OP_MKL_COMATADD                               "mkl_comatadd" },
    { FB_OP_MKL_COMATCOPY                              "mkl_comatcopy" },
    { FB_OP_MKL_COMATCOPY2                             "mkl_comatcopy2" },
    { FB_OP_MKL_COMATCOPY_BATCH                        "mkl_comatcopy_batch" },
    { FB_OP_MKL_COMATCOPY_BATCH_STRIDED                "mkl_comatcopy_batch_strided" },
    { FB_OP_MKL_DIMATCOPY                              "mkl_dimatcopy" },
    { FB_OP_MKL_DIMATCOPY_BATCH                        "mkl_dimatcopy_batch" },
    { FB_OP_MKL_DIMATCOPY_BATCH_STRIDED                "mkl_dimatcopy_batch_strided" },
    { FB_OP_MKL_DOMATADD                               "mkl_domatadd" },
    { FB_OP_MKL_DOMATCOPY                              "mkl_domatcopy" },
    { FB_OP_MKL_DOMATCOPY2                             "mkl_domatcopy2" },
    { FB_OP_MKL_DOMATCOPY_BATCH                        "mkl_domatcopy_batch" },
    { FB_OP_MKL_DOMATCOPY_BATCH_STRIDED                "mkl_domatcopy_batch_strided" },
    { FB_OP_MKL_JIT_CREATE_CGEMM                       "mkl_jit_create_cgemm" },
    { FB_OP_MKL_JIT_CREATE_DGEMM                       "mkl_jit_create_dgemm" },
    { FB_OP_MKL_JIT_CREATE_SGEMM                       "mkl_jit_create_sgemm" },
    { FB_OP_MKL_JIT_CREATE_ZGEMM                       "mkl_jit_create_zgemm" },
    { FB_OP_MKL_JIT_DESTROY                            "mkl_jit_destroy" },
    { FB_OP_MKL_JIT_GET_CGEMM_PTR                      "mkl_jit_get_cgemm_ptr" },
    { FB_OP_MKL_JIT_GET_DGEMM_PTR                      "mkl_jit_get_dgemm_ptr" },
    { FB_OP_MKL_JIT_GET_SGEMM_PTR                      "mkl_jit_get_sgemm_ptr" },
    { FB_OP_MKL_JIT_GET_ZGEMM_PTR                      "mkl_jit_get_zgemm_ptr" },
    { FB_OP_MKL_SIMATCOPY                              "mkl_simatcopy" },
    { FB_OP_MKL_SIMATCOPY_BATCH                        "mkl_simatcopy_batch" },
    { FB_OP_MKL_SIMATCOPY_BATCH_STRIDED                "mkl_simatcopy_batch_strided" },
    { FB_OP_MKL_SOMATADD                               "mkl_somatadd" },
    { FB_OP_MKL_SOMATCOPY                              "mkl_somatcopy" },
    { FB_OP_MKL_SOMATCOPY2                             "mkl_somatcopy2" },
    { FB_OP_MKL_SOMATCOPY_BATCH                        "mkl_somatcopy_batch" },
    { FB_OP_MKL_SOMATCOPY_BATCH_STRIDED                "mkl_somatcopy_batch_strided" },
    { FB_OP_MKL_SPARSE_S_CREATE_CSR                    "mkl_sparse_s_create_csr" },
    { FB_OP_MKL_SPARSE_S_MV                            "mkl_sparse_s_mv" },
    { FB_OP_MKL_ZIMATCOPY                              "mkl_zimatcopy" },
    { FB_OP_MKL_ZIMATCOPY_BATCH                        "mkl_zimatcopy_batch" },
    { FB_OP_MKL_ZIMATCOPY_BATCH_STRIDED                "mkl_zimatcopy_batch_strided" },
    { FB_OP_MKL_ZOMATADD                               "mkl_zomatadd" },
    { FB_OP_MKL_ZOMATCOPY                              "mkl_zomatcopy" },
    { FB_OP_MKL_ZOMATCOPY2                             "mkl_zomatcopy2" },
    { FB_OP_MKL_ZOMATCOPY_BATCH                        "mkl_zomatcopy_batch" },
    { FB_OP_MKL_ZOMATCOPY_BATCH_STRIDED                "mkl_zomatcopy_batch_strided" },
};

const size_t k_mkl_ext_symbols_count =
    sizeof(k_mkl_ext_symbols) / sizeof(k_mkl_ext_symbols[0]);
