/* AUTO-GENERATED by gen_sym_tables.py — do not edit by hand.
 * Re-run from workspace root:  python gen_sym_tables.py
 */

#ifndef FB_SYM_TABLES_H
#define FB_SYM_TABLES_H

/* fb_sym_entry_t is defined in the parent directory */
#include "../backend_auto_detect.h"

#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ── LAPACKE_* — OpenBLAS / MKL / AOCL-LAPACK  (IDs 157-1321) ─────────── */
extern const fb_sym_entry_t k_lapacke_symbols[];
extern const size_t         k_lapacke_symbols_count;

/* ── cblas_* extended/batch — MKL extensions  (IDs 1634-1807) ──────────── */
extern const fb_sym_entry_t k_cblas_ext_symbols[];
extern const size_t         k_cblas_ext_symbols_count;

/* ── mkl_* extensions — Intel MKL specific  (IDs 1808-1850) ────────────── */
extern const fb_sym_entry_t k_mkl_ext_symbols[];
extern const size_t         k_mkl_ext_symbols_count;

/* ── ScaLAPACK Fortran p*_ symbols  (IDs 1322-1633) ────────────────────── */
extern const fb_sym_entry_t k_scalapack_symbols[];
extern const size_t         k_scalapack_symbols_count;

/* ── cuBLAS / cuSolver symbol names  (IDs 0-1321) ──────────────────────── */
extern const fb_sym_entry_t k_cublas_symbols[];
extern const size_t         k_cublas_symbols_count;

/* ── rocBLAS / rocSOLVER symbol names  (IDs 0-1321) ────────────────────── */
extern const fb_sym_entry_t k_rocblas_symbols[];
extern const size_t         k_rocblas_symbols_count;

#ifdef __cplusplus
}
#endif

#endif /* FB_SYM_TABLES_H */
