/**
 * @file op_vtable_map.c
 * @brief Maps FB_OP_* IDs to named vtable fields; populates ext_ops[].
 *
 * Generated 237-entry table mapping every named function-pointer field in
 * fb_backend_vtable_t to its FB_OP_* constant, enabling uniform O(1)
 * op-level dispatch via vtable->ext_ops[].
 *
 * @copyright Copyright (c) 2025
 * @license MIT OR Apache-2.0
 */

#include <stddef.h>
#include <string.h>
#include <stdint.h>
#include "../backends/backend_interface.h"
#include "../judge/judge_op_ids.h"   /* FB_OP_* constants for the mapping table */

typedef struct {
    uint32_t  op_id;
    ptrdiff_t offset;
} fb_op_field_entry_t;

static const fb_op_field_entry_t k_op_field_map[] = {
    { FB_OP_SASUM,                                     offsetof(fb_backend_vtable_t, sasum) },
    { FB_OP_DASUM,                                     offsetof(fb_backend_vtable_t, dasum) },
    { FB_OP_SCASUM,                                    offsetof(fb_backend_vtable_t, scasum) },
    { FB_OP_DZASUM,                                    offsetof(fb_backend_vtable_t, dzasum) },
    { FB_OP_SAXPY,                                     offsetof(fb_backend_vtable_t, saxpy) },
    { FB_OP_DAXPY,                                     offsetof(fb_backend_vtable_t, daxpy) },
    { FB_OP_CAXPY,                                     offsetof(fb_backend_vtable_t, caxpy) },
    { FB_OP_ZAXPY,                                     offsetof(fb_backend_vtable_t, zaxpy) },
    { FB_OP_SCOPY,                                     offsetof(fb_backend_vtable_t, scopy) },
    { FB_OP_DCOPY,                                     offsetof(fb_backend_vtable_t, dcopy) },
    { FB_OP_CCOPY,                                     offsetof(fb_backend_vtable_t, ccopy) },
    { FB_OP_ZCOPY,                                     offsetof(fb_backend_vtable_t, zcopy) },
    { FB_OP_SDOT,                                      offsetof(fb_backend_vtable_t, sdot) },
    { FB_OP_DDOT,                                      offsetof(fb_backend_vtable_t, ddot) },
    { FB_OP_CDOTC,                                     offsetof(fb_backend_vtable_t, cdotc) },
    { FB_OP_ZDOTC,                                     offsetof(fb_backend_vtable_t, zdotc) },
    { FB_OP_CDOTU,                                     offsetof(fb_backend_vtable_t, cdotu) },
    { FB_OP_ZDOTU,                                     offsetof(fb_backend_vtable_t, zdotu) },
    { FB_OP_ZDROT,                                     offsetof(fb_backend_vtable_t, zdrot) },
    { FB_OP_SDSDOT,                                    offsetof(fb_backend_vtable_t, sdsdot) },
    { FB_OP_DSDOT,                                     offsetof(fb_backend_vtable_t, dsdot) },
    { FB_OP_ISAMAX,                                    offsetof(fb_backend_vtable_t, isamax) },
    { FB_OP_IDAMAX,                                    offsetof(fb_backend_vtable_t, idamax) },
    { FB_OP_ICAMAX,                                    offsetof(fb_backend_vtable_t, icamax) },
    { FB_OP_IZAMAX,                                    offsetof(fb_backend_vtable_t, izamax) },
    { FB_OP_SNRM2,                                     offsetof(fb_backend_vtable_t, snrm2) },
    { FB_OP_DNRM2,                                     offsetof(fb_backend_vtable_t, dnrm2) },
    { FB_OP_SCNRM2,                                    offsetof(fb_backend_vtable_t, scnrm2) },
    { FB_OP_DZNRM2,                                    offsetof(fb_backend_vtable_t, dznrm2) },
    { FB_OP_SROT,                                      offsetof(fb_backend_vtable_t, srot) },
    { FB_OP_DROT,                                      offsetof(fb_backend_vtable_t, drot) },
    { FB_OP_CROT,                                      offsetof(fb_backend_vtable_t, crot) },
    { FB_OP_ZROT,                                      offsetof(fb_backend_vtable_t, zrot) },
    { FB_OP_SROTG,                                     offsetof(fb_backend_vtable_t, srotg) },
    { FB_OP_DROTG,                                     offsetof(fb_backend_vtable_t, drotg) },
    { FB_OP_SROTM,                                     offsetof(fb_backend_vtable_t, srotm) },
    { FB_OP_DROTM,                                     offsetof(fb_backend_vtable_t, drotm) },
    { FB_OP_SROTMG,                                    offsetof(fb_backend_vtable_t, srotmg) },
    { FB_OP_DROTMG,                                    offsetof(fb_backend_vtable_t, drotmg) },
    { FB_OP_SSCAL,                                     offsetof(fb_backend_vtable_t, sscal) },
    { FB_OP_DSCAL,                                     offsetof(fb_backend_vtable_t, dscal) },
    { FB_OP_CSCAL,                                     offsetof(fb_backend_vtable_t, cscal) },
    { FB_OP_CSSCAL,                                    offsetof(fb_backend_vtable_t, csscal) },
    { FB_OP_ZSCAL,                                     offsetof(fb_backend_vtable_t, zscal) },
    { FB_OP_ZDSCAL,                                    offsetof(fb_backend_vtable_t, zdscal) },
    { FB_OP_SSWAP,                                     offsetof(fb_backend_vtable_t, sswap) },
    { FB_OP_DSWAP,                                     offsetof(fb_backend_vtable_t, dswap) },
    { FB_OP_CSWAP,                                     offsetof(fb_backend_vtable_t, cswap) },
    { FB_OP_ZSWAP,                                     offsetof(fb_backend_vtable_t, zswap) },
    { FB_OP_SGBMV,                                     offsetof(fb_backend_vtable_t, sgbmv) },
    { FB_OP_DGBMV,                                     offsetof(fb_backend_vtable_t, dgbmv) },
    { FB_OP_CGBMV,                                     offsetof(fb_backend_vtable_t, cgbmv) },
    { FB_OP_ZGBMV,                                     offsetof(fb_backend_vtable_t, zgbmv) },
    { FB_OP_SGEMV,                                     offsetof(fb_backend_vtable_t, sgemv) },
    { FB_OP_DGEMV,                                     offsetof(fb_backend_vtable_t, dgemv) },
    { FB_OP_CGEMV,                                     offsetof(fb_backend_vtable_t, cgemv) },
    { FB_OP_ZGEMV,                                     offsetof(fb_backend_vtable_t, zgemv) },
    { FB_OP_SGER,                                      offsetof(fb_backend_vtable_t, sger) },
    { FB_OP_DGER,                                      offsetof(fb_backend_vtable_t, dger) },
    { FB_OP_CGERC,                                     offsetof(fb_backend_vtable_t, cgerc) },
    { FB_OP_ZGERC,                                     offsetof(fb_backend_vtable_t, zgerc) },
    { FB_OP_CGERU,                                     offsetof(fb_backend_vtable_t, cgeru) },
    { FB_OP_ZGERU,                                     offsetof(fb_backend_vtable_t, zgeru) },
    { FB_OP_CHBMV,                                     offsetof(fb_backend_vtable_t, chbmv) },
    { FB_OP_ZHBMV,                                     offsetof(fb_backend_vtable_t, zhbmv) },
    { FB_OP_CHEMV,                                     offsetof(fb_backend_vtable_t, chemv) },
    { FB_OP_ZHEMV,                                     offsetof(fb_backend_vtable_t, zhemv) },
    { FB_OP_CHER,                                      offsetof(fb_backend_vtable_t, cher) },
    { FB_OP_ZHER,                                      offsetof(fb_backend_vtable_t, zher) },
    { FB_OP_CHER2,                                     offsetof(fb_backend_vtable_t, cher2) },
    { FB_OP_ZHER2,                                     offsetof(fb_backend_vtable_t, zher2) },
    { FB_OP_CHPMV,                                     offsetof(fb_backend_vtable_t, chpmv) },
    { FB_OP_ZHPMV,                                     offsetof(fb_backend_vtable_t, zhpmv) },
    { FB_OP_CHPR,                                      offsetof(fb_backend_vtable_t, chpr) },
    { FB_OP_ZHPR,                                      offsetof(fb_backend_vtable_t, zhpr) },
    { FB_OP_CHPR2,                                     offsetof(fb_backend_vtable_t, chpr2) },
    { FB_OP_ZHPR2,                                     offsetof(fb_backend_vtable_t, zhpr2) },
    { FB_OP_SSBMV,                                     offsetof(fb_backend_vtable_t, ssbmv) },
    { FB_OP_DSBMV,                                     offsetof(fb_backend_vtable_t, dsbmv) },
    { FB_OP_SSPMV,                                     offsetof(fb_backend_vtable_t, sspmv) },
    { FB_OP_DSPMV,                                     offsetof(fb_backend_vtable_t, dspmv) },
    { FB_OP_SSPR,                                      offsetof(fb_backend_vtable_t, sspr) },
    { FB_OP_DSPR,                                      offsetof(fb_backend_vtable_t, dspr) },
    { FB_OP_SSPR2,                                     offsetof(fb_backend_vtable_t, sspr2) },
    { FB_OP_DSPR2,                                     offsetof(fb_backend_vtable_t, dspr2) },
    { FB_OP_SSYMV,                                     offsetof(fb_backend_vtable_t, ssymv) },
    { FB_OP_DSYMV,                                     offsetof(fb_backend_vtable_t, dsymv) },
    { FB_OP_SSYR,                                      offsetof(fb_backend_vtable_t, ssyr) },
    { FB_OP_DSYR,                                      offsetof(fb_backend_vtable_t, dsyr) },
    { FB_OP_SSYR2,                                     offsetof(fb_backend_vtable_t, ssyr2) },
    { FB_OP_DSYR2,                                     offsetof(fb_backend_vtable_t, dsyr2) },
    { FB_OP_STBMV,                                     offsetof(fb_backend_vtable_t, stbmv) },
    { FB_OP_DTBMV,                                     offsetof(fb_backend_vtable_t, dtbmv) },
    { FB_OP_CTBMV,                                     offsetof(fb_backend_vtable_t, ctbmv) },
    { FB_OP_ZTBMV,                                     offsetof(fb_backend_vtable_t, ztbmv) },
    { FB_OP_STBSV,                                     offsetof(fb_backend_vtable_t, stbsv) },
    { FB_OP_DTBSV,                                     offsetof(fb_backend_vtable_t, dtbsv) },
    { FB_OP_CTBSV,                                     offsetof(fb_backend_vtable_t, ctbsv) },
    { FB_OP_ZTBSV,                                     offsetof(fb_backend_vtable_t, ztbsv) },
    { FB_OP_STPMV,                                     offsetof(fb_backend_vtable_t, stpmv) },
    { FB_OP_DTPMV,                                     offsetof(fb_backend_vtable_t, dtpmv) },
    { FB_OP_CTPMV,                                     offsetof(fb_backend_vtable_t, ctpmv) },
    { FB_OP_ZTPMV,                                     offsetof(fb_backend_vtable_t, ztpmv) },
    { FB_OP_STPSV,                                     offsetof(fb_backend_vtable_t, stpsv) },
    { FB_OP_DTPSV,                                     offsetof(fb_backend_vtable_t, dtpsv) },
    { FB_OP_CTPSV,                                     offsetof(fb_backend_vtable_t, ctpsv) },
    { FB_OP_ZTPSV,                                     offsetof(fb_backend_vtable_t, ztpsv) },
    { FB_OP_STRMV,                                     offsetof(fb_backend_vtable_t, strmv) },
    { FB_OP_DTRMV,                                     offsetof(fb_backend_vtable_t, dtrmv) },
    { FB_OP_CTRMV,                                     offsetof(fb_backend_vtable_t, ctrmv) },
    { FB_OP_ZTRMV,                                     offsetof(fb_backend_vtable_t, ztrmv) },
    { FB_OP_STRSV,                                     offsetof(fb_backend_vtable_t, strsv) },
    { FB_OP_DTRSV,                                     offsetof(fb_backend_vtable_t, dtrsv) },
    { FB_OP_CTRSV,                                     offsetof(fb_backend_vtable_t, ctrsv) },
    { FB_OP_ZTRSV,                                     offsetof(fb_backend_vtable_t, ztrsv) },
    { FB_OP_SGEMM,                                     offsetof(fb_backend_vtable_t, sgemm) },
    { FB_OP_DGEMM,                                     offsetof(fb_backend_vtable_t, dgemm) },
    { FB_OP_CGEMM,                                     offsetof(fb_backend_vtable_t, cgemm) },
    { FB_OP_ZGEMM,                                     offsetof(fb_backend_vtable_t, zgemm) },
    { FB_OP_CHEMM,                                     offsetof(fb_backend_vtable_t, chemm) },
    { FB_OP_ZHEMM,                                     offsetof(fb_backend_vtable_t, zhemm) },
    { FB_OP_CHER2K,                                    offsetof(fb_backend_vtable_t, cher2k) },
    { FB_OP_ZHER2K,                                    offsetof(fb_backend_vtable_t, zher2k) },
    { FB_OP_CHERK,                                     offsetof(fb_backend_vtable_t, cherk) },
    { FB_OP_ZHERK,                                     offsetof(fb_backend_vtable_t, zherk) },
    { FB_OP_SSYMM,                                     offsetof(fb_backend_vtable_t, ssymm) },
    { FB_OP_DSYMM,                                     offsetof(fb_backend_vtable_t, dsymm) },
    { FB_OP_CSYMM,                                     offsetof(fb_backend_vtable_t, csymm) },
    { FB_OP_ZSYMM,                                     offsetof(fb_backend_vtable_t, zsymm) },
    { FB_OP_SSYR2K,                                    offsetof(fb_backend_vtable_t, ssyr2k) },
    { FB_OP_DSYR2K,                                    offsetof(fb_backend_vtable_t, dsyr2k) },
    { FB_OP_CSYR2K,                                    offsetof(fb_backend_vtable_t, csyr2k) },
    { FB_OP_ZSYR2K,                                    offsetof(fb_backend_vtable_t, zsyr2k) },
    { FB_OP_SSYRK,                                     offsetof(fb_backend_vtable_t, ssyrk) },
    { FB_OP_DSYRK,                                     offsetof(fb_backend_vtable_t, dsyrk) },
    { FB_OP_CSYRK,                                     offsetof(fb_backend_vtable_t, csyrk) },
    { FB_OP_ZSYRK,                                     offsetof(fb_backend_vtable_t, zsyrk) },
    { FB_OP_STRMM,                                     offsetof(fb_backend_vtable_t, strmm) },
    { FB_OP_DTRMM,                                     offsetof(fb_backend_vtable_t, dtrmm) },
    { FB_OP_CTRMM,                                     offsetof(fb_backend_vtable_t, ctrmm) },
    { FB_OP_ZTRMM,                                     offsetof(fb_backend_vtable_t, ztrmm) },
    { FB_OP_STRSM,                                     offsetof(fb_backend_vtable_t, strsm) },
    { FB_OP_DTRSM,                                     offsetof(fb_backend_vtable_t, dtrsm) },
    { FB_OP_CTRSM,                                     offsetof(fb_backend_vtable_t, ctrsm) },
    { FB_OP_ZTRSM,                                     offsetof(fb_backend_vtable_t, ztrsm) },
    { FB_OP_SGEEV,                                     offsetof(fb_backend_vtable_t, sgeev) },
    { FB_OP_DGEEV,                                     offsetof(fb_backend_vtable_t, dgeev) },
    { FB_OP_CGEEV,                                     offsetof(fb_backend_vtable_t, cgeev) },
    { FB_OP_ZGEEV,                                     offsetof(fb_backend_vtable_t, zgeev) },
    { FB_OP_SGELS,                                     offsetof(fb_backend_vtable_t, sgels) },
    { FB_OP_DGELS,                                     offsetof(fb_backend_vtable_t, dgels) },
    { FB_OP_CGELS,                                     offsetof(fb_backend_vtable_t, cgels) },
    { FB_OP_ZGELS,                                     offsetof(fb_backend_vtable_t, zgels) },
    { FB_OP_SGELSD,                                    offsetof(fb_backend_vtable_t, sgelsd) },
    { FB_OP_DGELSD,                                    offsetof(fb_backend_vtable_t, dgelsd) },
    { FB_OP_CGELSD,                                    offsetof(fb_backend_vtable_t, cgelsd) },
    { FB_OP_ZGELSD,                                    offsetof(fb_backend_vtable_t, zgelsd) },
    { FB_OP_SGELSY,                                    offsetof(fb_backend_vtable_t, sgelsy) },
    { FB_OP_DGELSY,                                    offsetof(fb_backend_vtable_t, dgelsy) },
    { FB_OP_CGELSY,                                    offsetof(fb_backend_vtable_t, cgelsy) },
    { FB_OP_ZGELSY,                                    offsetof(fb_backend_vtable_t, zgelsy) },
    { FB_OP_SGEQRF,                                    offsetof(fb_backend_vtable_t, sgeqrf) },
    { FB_OP_DGEQRF,                                    offsetof(fb_backend_vtable_t, dgeqrf) },
    { FB_OP_CGEQRF,                                    offsetof(fb_backend_vtable_t, cgeqrf) },
    { FB_OP_ZGEQRF,                                    offsetof(fb_backend_vtable_t, zgeqrf) },
    { FB_OP_SGESDD,                                    offsetof(fb_backend_vtable_t, sgesdd) },
    { FB_OP_DGESDD,                                    offsetof(fb_backend_vtable_t, dgesdd) },
    { FB_OP_CGESDD,                                    offsetof(fb_backend_vtable_t, cgesdd) },
    { FB_OP_ZGESDD,                                    offsetof(fb_backend_vtable_t, zgesdd) },
    { FB_OP_SGESV,                                     offsetof(fb_backend_vtable_t, sgesv) },
    { FB_OP_DGESV,                                     offsetof(fb_backend_vtable_t, dgesv) },
    { FB_OP_CGESV,                                     offsetof(fb_backend_vtable_t, cgesv) },
    { FB_OP_ZGESV,                                     offsetof(fb_backend_vtable_t, zgesv) },
    { FB_OP_SGESVD,                                    offsetof(fb_backend_vtable_t, sgesvd) },
    { FB_OP_DGESVD,                                    offsetof(fb_backend_vtable_t, dgesvd) },
    { FB_OP_CGESVD,                                    offsetof(fb_backend_vtable_t, cgesvd) },
    { FB_OP_ZGESVD,                                    offsetof(fb_backend_vtable_t, zgesvd) },
    { FB_OP_SGETRF,                                    offsetof(fb_backend_vtable_t, sgetrf) },
    { FB_OP_DGETRF,                                    offsetof(fb_backend_vtable_t, dgetrf) },
    { FB_OP_CGETRF,                                    offsetof(fb_backend_vtable_t, cgetrf) },
    { FB_OP_ZGETRF,                                    offsetof(fb_backend_vtable_t, zgetrf) },
    { FB_OP_SGETRI,                                    offsetof(fb_backend_vtable_t, sgetri) },
    { FB_OP_DGETRI,                                    offsetof(fb_backend_vtable_t, dgetri) },
    { FB_OP_CGETRI,                                    offsetof(fb_backend_vtable_t, cgetri) },
    { FB_OP_ZGETRI,                                    offsetof(fb_backend_vtable_t, zgetri) },
    { FB_OP_SGETRS,                                    offsetof(fb_backend_vtable_t, sgetrs) },
    { FB_OP_DGETRS,                                    offsetof(fb_backend_vtable_t, dgetrs) },
    { FB_OP_CGETRS,                                    offsetof(fb_backend_vtable_t, cgetrs) },
    { FB_OP_ZGETRS,                                    offsetof(fb_backend_vtable_t, zgetrs) },
    { FB_OP_CHEEV,                                     offsetof(fb_backend_vtable_t, cheev) },
    { FB_OP_ZHEEV,                                     offsetof(fb_backend_vtable_t, zheev) },
    { FB_OP_CHEGV,                                     offsetof(fb_backend_vtable_t, chegv) },
    { FB_OP_ZHEGV,                                     offsetof(fb_backend_vtable_t, zhegv) },
    { FB_OP_CHESV,                                     offsetof(fb_backend_vtable_t, chesv) },
    { FB_OP_ZHESV,                                     offsetof(fb_backend_vtable_t, zhesv) },
    { FB_OP_SORGQR,                                    offsetof(fb_backend_vtable_t, sorgqr) },
    { FB_OP_DORGQR,                                    offsetof(fb_backend_vtable_t, dorgqr) },
    { FB_OP_SORMQR,                                    offsetof(fb_backend_vtable_t, sormqr) },
    { FB_OP_DORMQR,                                    offsetof(fb_backend_vtable_t, dormqr) },
    { FB_OP_SPOSV,                                     offsetof(fb_backend_vtable_t, sposv) },
    { FB_OP_DPOSV,                                     offsetof(fb_backend_vtable_t, dposv) },
    { FB_OP_CPOSV,                                     offsetof(fb_backend_vtable_t, cposv) },
    { FB_OP_ZPOSV,                                     offsetof(fb_backend_vtable_t, zposv) },
    { FB_OP_SPOTRF,                                    offsetof(fb_backend_vtable_t, spotrf) },
    { FB_OP_DPOTRF,                                    offsetof(fb_backend_vtable_t, dpotrf) },
    { FB_OP_CPOTRF,                                    offsetof(fb_backend_vtable_t, cpotrf) },
    { FB_OP_ZPOTRF,                                    offsetof(fb_backend_vtable_t, zpotrf) },
    { FB_OP_SPOTRI,                                    offsetof(fb_backend_vtable_t, spotri) },
    { FB_OP_DPOTRI,                                    offsetof(fb_backend_vtable_t, dpotri) },
    { FB_OP_CPOTRI,                                    offsetof(fb_backend_vtable_t, cpotri) },
    { FB_OP_ZPOTRI,                                    offsetof(fb_backend_vtable_t, zpotri) },
    { FB_OP_SPOTRS,                                    offsetof(fb_backend_vtable_t, spotrs) },
    { FB_OP_DPOTRS,                                    offsetof(fb_backend_vtable_t, dpotrs) },
    { FB_OP_CPOTRS,                                    offsetof(fb_backend_vtable_t, cpotrs) },
    { FB_OP_ZPOTRS,                                    offsetof(fb_backend_vtable_t, zpotrs) },
    { FB_OP_CROTG,                                     offsetof(fb_backend_vtable_t, crotg) },
    { FB_OP_ZROTG,                                     offsetof(fb_backend_vtable_t, zrotg) },
    { FB_OP_SSYEV,                                     offsetof(fb_backend_vtable_t, ssyev) },
    { FB_OP_DSYEV,                                     offsetof(fb_backend_vtable_t, dsyev) },
    { FB_OP_SSYGV,                                     offsetof(fb_backend_vtable_t, ssygv) },
    { FB_OP_DSYGV,                                     offsetof(fb_backend_vtable_t, dsygv) },
    { FB_OP_CSYMV,                                     offsetof(fb_backend_vtable_t, csymv) },
    { FB_OP_ZSYMV,                                     offsetof(fb_backend_vtable_t, zsymv) },
    { FB_OP_CSYR,                                      offsetof(fb_backend_vtable_t, csyr) },
    { FB_OP_ZSYR,                                      offsetof(fb_backend_vtable_t, zsyr) },
    { FB_OP_SSYSV,                                     offsetof(fb_backend_vtable_t, ssysv) },
    { FB_OP_DSYSV,                                     offsetof(fb_backend_vtable_t, dsysv) },
    { FB_OP_CSYSV,                                     offsetof(fb_backend_vtable_t, csysv) },
    { FB_OP_ZSYSV,                                     offsetof(fb_backend_vtable_t, zsysv) },
    { FB_OP_STRTRI,                                    offsetof(fb_backend_vtable_t, strtri) },
    { FB_OP_DTRTRI,                                    offsetof(fb_backend_vtable_t, dtrtri) },
    { FB_OP_CTRTRI,                                    offsetof(fb_backend_vtable_t, ctrtri) },
    { FB_OP_ZTRTRI,                                    offsetof(fb_backend_vtable_t, ztrtri) },
    { FB_OP_CUNGQR,                                    offsetof(fb_backend_vtable_t, cungqr) },
    { FB_OP_ZUNGQR,                                    offsetof(fb_backend_vtable_t, zungqr) },
    { FB_OP_CUNMQR,                                    offsetof(fb_backend_vtable_t, cunmqr) },
    { FB_OP_ZUNMQR,                                    offsetof(fb_backend_vtable_t, zunmqr) },
};

#define K_OP_FIELD_MAP_COUNT \
    ((int)(sizeof(k_op_field_map) / sizeof(k_op_field_map[0])))

void fb_vtable_sync_ext_ops(fb_backend_vtable_t *v) {
    if (!v) return;
    for (int i = 0; i < K_OP_FIELD_MAP_COUNT; i++) {
        uint32_t  op_id = k_op_field_map[i].op_id;
        ptrdiff_t off   = k_op_field_map[i].offset;
        fb_generic_fn fn = NULL;
        memcpy(&fn, (const char *)v + off, sizeof(fb_generic_fn));
        if (fn != NULL && v->ext_ops[op_id] == NULL) {
            v->ext_ops[op_id] = fn;
        }
    }
}

fb_generic_fn fb_vtable_get_op(const fb_backend_vtable_t *v, uint32_t op_id) {
    if (!v || op_id >= (uint32_t)FB_JUDGE_MAX_OPERATIONS) return NULL;
    return v->ext_ops[op_id];
}
