/**
 * @file vtable_dispatchers_gemm.c
 * @brief Unified GEMM dispatcher from specific operations
 *
 * This file contains the gemm_unified() dispatcher that routes to specific
 * BLAS operations (sgemm, dgemm, cgemm, zgemm) based on precision flags.
 * This enables backends that provide only specific operations to work with
 * the unified GEMM API.
 *
 * Generated by Phase 2.4 of vtable auto-fill system.
 *
 * @copyright Copyright (c) 2025-2026
 * @license MIT OR Apache-2.0
 */

#include "../../include/faster-blaster/vtable_autofill.h"
#include "../backends/backend_interface.h"
#include <stddef.h>

/**
 * @brief Unified GEMM dispatcher implementation
 *
 * Routes unified GEMM calls to specific precision implementations.
 * This implementation:
 * - Dispatches to sgemm/dgemm/cgemm/zgemm based on precision enum
 * - Converts char transpose flags to fb_transpose_t enums
 * - Handles single-batch operations (batch_count=1, strideA/B/C=0)
 * - Returns error for unsupported features (batching, fusion, mixed-precision)
 *
 * @param precision Precision selector (FP32→sgemm, FP64→dgemm, etc.)
 * @param batch_mode Batch mode (only FB_BATCH_SINGLE supported)
 * @param fusion Fusion mode (only FB_FUSION_NONE supported)
 * @param transa Transpose flag for A ('N', 'T', 'C')
 * @param transb Transpose flag for B ('N', 'T', 'C')
 * @param m Number of rows in A and C
 * @param n Number of columns in B and C
 * @param k Number of columns in A (rows in B)
 * @param alpha Scalar multiplier for A*B
 * @param A Matrix A (m x k if no transpose, k x m if transpose)
 * @param lda Leading dimension of A
 * @param strideA Stride between batches (must be 0 for single batch)
 * @param B Matrix B (k x n if no transpose, n x k if transpose)
 * @param ldb Leading dimension of B
 * @param strideB Stride between batches (must be 0)
 * @param beta Scalar multiplier for C
 * @param C Matrix C (m x n)
 * @param ldc Leading dimension of C
 * @param strideC Stride between batches (must be 0)
 * @param bias Bias vector (must be NULL - not supported)
 * @param activation Activation function (must be FB_ACT_NONE)
 * @param batch_count Number of batches (must be 1)
 * @param stream Execution stream (ignored)
 * @return FB_STATUS_SUCCESS on success, error code otherwise
 */
fb_status_t fb_gemm_unified_from_specific(
    fb_precision_t precision, fb_batch_mode_t batch_mode, fb_fusion_t fusion,
    const char transa, const char transb, const size_t m, const size_t n,
    const size_t k, const void *alpha, const void *A, const size_t lda,
    const size_t strideA, const void *B, const size_t ldb, const size_t strideB,
    const void *beta, void *C, const size_t ldc, const size_t strideC,
    const void *bias, fb_activation_t activation, const size_t batch_count,
    void *stream) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable) {
    return FB_STATUS_ERROR;
  }

  /* Validate supported features */
  if (batch_mode != FB_BATCH_SINGLE || batch_count != 1) {
    return FB_STATUS_NOT_SUPPORTED; /* Batching requires specific batch ops */
  }
  if (fusion != FB_FUSION_NONE || activation != FB_ACT_NONE || bias != NULL) {
    return FB_STATUS_NOT_SUPPORTED; /* Fusion requires backend native support */
  }
  if (strideA != 0 || strideB != 0 || strideC != 0) {
    return FB_STATUS_INVALID_ARGUMENT; /* Strides must be 0 for single batch */
  }

  /* Convert char transpose flags to enums */
  fb_transpose_t trans_a, trans_b;
  if (transa == 'N' || transa == 'n') {
    trans_a = FB_NO_TRANS;
  } else if (transa == 'T' || transa == 't') {
    trans_a = FB_TRANS;
  } else if (transa == 'C' || transa == 'c') {
    trans_a = FB_CONJ_TRANS;
  } else {
    return FB_STATUS_INVALID_ARGUMENT;
  }

  if (transb == 'N' || transb == 'n') {
    trans_b = FB_NO_TRANS;
  } else if (transb == 'T' || transb == 't') {
    trans_b = FB_TRANS;
  } else if (transb == 'C' || transb == 'c') {
    trans_b = FB_CONJ_TRANS;
  } else {
    return FB_STATUS_INVALID_ARGUMENT;
  }

  /* Convert fb_layout_t for CBLAS operations (assume column-major) */
  const fb_layout_t layout = FB_COL_MAJOR;

  /* Dispatch based on precision */
  switch (precision) {
  case FB_PREC_FP32:
    if (!vtable->sgemm) {
      return FB_STATUS_NOT_SUPPORTED;
    }
    vtable->sgemm(layout, trans_a, trans_b, (int64_t)m, (int64_t)n, (int64_t)k,
                  *(const float *)alpha, (const float *)A, (int64_t)lda,
                  (const float *)B, (int64_t)ldb, *(const float *)beta,
                  (float *)C, (int64_t)ldc);
    return FB_STATUS_SUCCESS;

  case FB_PREC_FP64:
    if (!vtable->dgemm) {
      return FB_STATUS_NOT_SUPPORTED;
    }
    vtable->dgemm(layout, trans_a, trans_b, (int64_t)m, (int64_t)n, (int64_t)k,
                  *(const double *)alpha, (const double *)A, (int64_t)lda,
                  (const double *)B, (int64_t)ldb, *(const double *)beta,
                  (double *)C, (int64_t)ldc);
    return FB_STATUS_SUCCESS;

  case FB_PREC_C64:
    if (!vtable->cgemm) {
      return FB_STATUS_NOT_SUPPORTED;
    }
    vtable->cgemm(layout, trans_a, trans_b, (int64_t)m, (int64_t)n, (int64_t)k,
                  (const fb_complex_float_t *)alpha,
                  (const fb_complex_float_t *)A, (int64_t)lda,
                  (const fb_complex_float_t *)B, (int64_t)ldb,
                  (const fb_complex_float_t *)beta, (fb_complex_float_t *)C,
                  (int64_t)ldc);
    return FB_STATUS_SUCCESS;

  case FB_PREC_C128:
    if (!vtable->zgemm) {
      return FB_STATUS_NOT_SUPPORTED;
    }
    vtable->zgemm(layout, trans_a, trans_b, (int64_t)m, (int64_t)n, (int64_t)k,
                  (const fb_complex_double_t *)alpha,
                  (const fb_complex_double_t *)A, (int64_t)lda,
                  (const fb_complex_double_t *)B, (int64_t)ldb,
                  (const fb_complex_double_t *)beta, (fb_complex_double_t *)C,
                  (int64_t)ldc);
    return FB_STATUS_SUCCESS;

  case FB_PREC_FP16:
  case FB_PREC_BF16:
  case FB_PREC_FP8:
  case FB_PREC_INT8:
  case FB_PREC_INT32:
    /* Low-precision GEMM requires specialized kernels */
    return FB_STATUS_NOT_SUPPORTED;

  default:
    return FB_STATUS_INVALID_ARGUMENT;
  }
}

/**
 * @brief Install unified GEMM dispatcher from specific operations
 *
 * This function checks if gemm_unified is NULL but specific GEMM operations
 * (sgemm, dgemm, cgemm, zgemm) exist. If so, it installs the dispatcher.
 * This is called by fb_autofill_specific_to_unified() in Strategy 1.
 *
 * @param vtable Vtable to fill with unified GEMM dispatcher
 */
void fb_autofill_gemm_unified_from_specific(fb_backend_vtable_t *vtable) {
  if (!vtable) {
    return;
  }

  /* Only install if unified is missing AND at least one specific op exists */
  if (vtable->gemm_unified == NULL) {
    if (vtable->sgemm != NULL || vtable->dgemm != NULL ||
        vtable->cgemm != NULL || vtable->zgemm != NULL) {
      vtable->gemm_unified = fb_gemm_unified_from_specific;
    }
  }
}
