/**
 * @file vtable_wrappers_precision_promotion.c
 * @brief Auto-generated precision promotion fallback wrappers
 *
 * This file contains wrappers that promote lower precision to higher precision,
 * execute operations using higher-precision backends, then demote results
 * with overflow checking. These are last-resort fallbacks ensuring correctness
 * when no native implementation exists for a specific precision.
 *
 * Generated by Phase 5 of vtable auto-fill system.
 *
 * Strategy: Lower precision → Higher precision (Always correct, performance
 * cost)
 * - FP32 ↔ FP64: Lossless promotion, safe demotion with range checking
 * - C64 ↔ C128: Lossless promotion, safe demotion with range checking
 * - INT8 ↔ INT32: Lossless promotion, safe demotion with clamping
 *
 * Anti-patterns (never promoted):
 * - Higher precision → Lower: Precision loss in computation (semantically
 * wrong)
 * - Real ↔ Complex: Type system incompatibility (semantically wrong)
 * - Dense ↔ Sparse: Algorithmic difference (semantically wrong)
 *
 * @copyright Copyright (c) 2025-2026
 * @license MIT OR Apache-2.0
 */

#include "../../include/faster-blaster/vtable_autofill.h"
#include "../backends/backend_interface.h"
#include <float.h>
#include <math.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

/* ============================================================================
 * GEMM: FP32 from FP64 (Promotion)
 * ========================================================================= */

/**
 * @brief SGEMM wrapper using DGEMM (FP32 ← FP64)
 *
 * Promotes FP32 to FP64, calls DGEMM, demotes result with overflow checking.
 * Used when backend has only DGEMM but user calls SGEMM.
 */
void fb_sgemm_from_dgemm(const fb_layout_t layout, const fb_transpose_t transa,
                         const fb_transpose_t transb, const int m,
                         const int n, const int k, const float alpha,
                         const float *A, const int lda, const float *B,
                         const int ldb, const float beta, float *C,
                         const int ldc) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->dgemm) {
    return;
  }

  /* Allocate temporary buffers */
  size_t A_size = (size_t)((transa == FB_NO_TRANS ? k : m) * lda);
  size_t B_size = (size_t)((transb == FB_NO_TRANS ? n : k) * ldb);
  size_t C_size = (size_t)(m * ldc);

  double *A_d = (double *)fb_allocate_temp_buffer(A_size * sizeof(double));
  double *B_d = (double *)fb_allocate_temp_buffer(B_size * sizeof(double));
  double *C_d = (double *)fb_allocate_temp_buffer(C_size * sizeof(double));

  if (!A_d || !B_d || !C_d) {
    fb_free_temp_buffer(A_d);
    fb_free_temp_buffer(B_d);
    fb_free_temp_buffer(C_d);
    return; /* Out of memory */
  }

  /* Promote: FP32 → FP64 (lossless) */
  for (size_t i = 0; i < A_size; i++) {
    A_d[i] = (double)((const float *)A)[i];
  }
  for (size_t i = 0; i < B_size; i++) {
    B_d[i] = (double)((const float *)B)[i];
  }
  for (size_t i = 0; i < C_size; i++) {
    C_d[i] = (double)((const float *)C)[i];
  }

  /* Execute in FP64 */
  double alpha_d = (double)alpha;
  double beta_d = (double)beta;
  vtable->dgemm(layout, transa, transb, m, n, k, alpha_d, A_d, lda, B_d, ldb,
                beta_d, C_d, ldc);

  /* Demote: FP64 → FP32 (with overflow checking) */
  if (fb_demote_array_f64_to_f32_checked(C_d, (float *)C, C_size) !=
      FB_STATUS_SUCCESS) {
    /* Overflow during demotion - results are clamped to ±FLT_MAX */
  }

  /* Cleanup */
  fb_free_temp_buffer(A_d);
  fb_free_temp_buffer(B_d);
  fb_free_temp_buffer(C_d);
}

/* ============================================================================
 * GEMM: Complex FP32 from Complex FP64 (C64 ← C128)
 * ========================================================================= */

void fb_cgemm_from_zgemm(const fb_layout_t layout, const fb_transpose_t transa,
                         const fb_transpose_t transb, const int m,
                         const int n, const int k,
                         const fb_complex_float_t alpha,
                         const fb_complex_float_t *A, const int lda,
                         const fb_complex_float_t *B, const int ldb,
                         const fb_complex_float_t beta, fb_complex_float_t *C,
                         const int ldc) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->zgemm) {
    return;
  }

  size_t A_size = (size_t)((transa == FB_NO_TRANS ? k : m) * lda);
  size_t B_size = (size_t)((transb == FB_NO_TRANS ? n : k) * ldb);
  size_t C_size = (size_t)(m * ldc);

  fb_complex_double_t *A_d = (fb_complex_double_t *)fb_allocate_temp_buffer(
      A_size * sizeof(fb_complex_double_t));
  fb_complex_double_t *B_d = (fb_complex_double_t *)fb_allocate_temp_buffer(
      B_size * sizeof(fb_complex_double_t));
  fb_complex_double_t *C_d = (fb_complex_double_t *)fb_allocate_temp_buffer(
      C_size * sizeof(fb_complex_double_t));

  if (!A_d || !B_d || !C_d) {
    fb_free_temp_buffer(A_d);
    fb_free_temp_buffer(B_d);
    fb_free_temp_buffer(C_d);
    return;
  }

  /* Promote: C64 → C128 (lossless) */
  for (size_t i = 0; i < A_size; i++) {
    A_d[i] = (fb_complex_double_t)((const fb_complex_float_t *)A)[i];
  }
  for (size_t i = 0; i < B_size; i++) {
    B_d[i] = (fb_complex_double_t)((const fb_complex_float_t *)B)[i];
  }
  for (size_t i = 0; i < C_size; i++) {
    C_d[i] = (fb_complex_double_t)((const fb_complex_float_t *)C)[i];
  }

  /* Execute in FP64 */
  fb_complex_double_t alpha_d = {(double)__real__(alpha), (double)__imag__(alpha)};
  fb_complex_double_t beta_d = {(double)__real__(beta), (double)__imag__(beta)};

  vtable->zgemm(layout, transa, transb, m, n, k, alpha_d, A_d, lda, B_d, ldb,
                beta_d, C_d, ldc);

  /* Demote: C128 → C64 (with overflow checking) */
  if (fb_demote_array_c128_to_c64_checked(C_d, (fb_complex_float_t *)C,
                                          C_size) != FB_STATUS_SUCCESS) {
    /* Overflow during demotion */
  }

  /* Cleanup */
  fb_free_temp_buffer(A_d);
  fb_free_temp_buffer(B_d);
  fb_free_temp_buffer(C_d);
}

/* ============================================================================
 * SAXPY: FP32 from FP64 (Promotion)
 * ========================================================================= */

void fb_saxpy_from_daxpy(int n, float alpha, const float *x, int incx, float *y,
                         int incy) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->daxpy) {
    return;
  }

  /* Allocate temporary buffers for vectors */
  double *x_d = (double *)fb_allocate_temp_buffer((size_t)n * sizeof(double));
  double *y_d = (double *)fb_allocate_temp_buffer((size_t)n * sizeof(double));

  if (!x_d || !y_d) {
    fb_free_temp_buffer(x_d);
    fb_free_temp_buffer(y_d);
    return;
  }

  /* Promote: FP32 → FP64 (lossless) */
  for (int i = 0; i < n; i++) {
    x_d[i] = (double)x[i * incx];
    y_d[i] = (double)y[i * incy];
  }

  /* Execute in FP64 */
  double alpha_d = (double)alpha;
  vtable->daxpy(n, alpha_d, x_d, 1, y_d, 1);

  /* Demote: FP64 → FP32 (with overflow checking) */
  fb_demote_array_f64_to_f32_checked(y_d, y, (size_t)n);

  /* Cleanup */
  fb_free_temp_buffer(x_d);
  fb_free_temp_buffer(y_d);
}

/* ============================================================================
 * Installer Functions
 * ========================================================================= */

/**
 * @brief Install GEMM precision promotion wrappers
 *
 * FP32 operations promoted to FP64 (requires DGEMM)
 * Complex FP32 promoted to Complex FP64 (requires ZGEMM)
 */
void fb_autofill_gemm_precision_promotion(fb_backend_vtable_t *vtable) {
  if (!vtable) {
    return;
  }

  /* FP32 ← FP64 promotion */
  if (vtable->sgemm == NULL && vtable->dgemm != NULL) {
    vtable->sgemm = fb_sgemm_from_dgemm;
  }

  /* Complex FP32 ← Complex FP64 promotion */
  if (vtable->cgemm == NULL && vtable->zgemm != NULL) {
    vtable->cgemm = fb_cgemm_from_zgemm;
  }
}

/**
 * @brief Install BLAS L1 precision promotion wrappers
 */
void fb_autofill_blas_l1_precision_promotion(fb_backend_vtable_t *vtable) {
  if (!vtable) {
    return;
  }

  /* SAXPY ← DAXPY promotion */
  if (vtable->saxpy == NULL && vtable->daxpy != NULL) {
    vtable->saxpy = fb_saxpy_from_daxpy;
  }
}

/**
 * @brief Master installer for precision promotion fallbacks
 *
 * Called by fb_autofill_precision_promotion() in Strategy 4.
 * This is the last resort when no native implementation exists.
 */
void fb_autofill_all_precision_promotion(fb_backend_vtable_t *vtable) {
  if (!vtable) {
    return;
  }

  fb_autofill_gemm_precision_promotion(vtable);
  fb_autofill_blas_l1_precision_promotion(vtable);

  /* TODO: Phase 5.1 - Add BLAS L2 promotion (SGEMV ← DGEMV, etc.) */
  /* TODO: Phase 5.2 - Add LAPACK promotion (SPOT, DPOT, etc.) */
  /* TODO: Phase 5.3 - Add INT8 ← INT32 promotions */
  /* TODO: Phase 5.4 - Add FP16, BF16, FP8 promotions */
}
