/**
 * @file vtable_wrappers_batched.c
 * @brief Auto-generated single-operation wrappers from batched operations
 *
 * This file contains wrappers that call batched operations (strided or
 * array-based) with batch_count=1. These enable backends that provide only
 * batched GEMM operations to work with single-operation calls.
 *
 * Generated by Phase 3 of vtable auto-fill system.
 *
 * @copyright Copyright (c) 2025-2026
 * @license MIT OR Apache-2.0
 */

#include "../../include/faster-blaster/vtable_autofill.h"
#include "../backends/backend_interface.h"
#include <stddef.h>
#include <stdlib.h>
#include <string.h>

/* These wrappers require extended vtable with batched GEMM operations.
 * Guard compilation until vtable is extended. */
#ifdef FB_EXTENDED_VTABLE_SUPPORT

/* ============================================================================
 * GEMM Single from Batched (Strided): SGEMM
 * ========================================================================= */

void fb_sgemm_from_sgemm_batch_strided(
    const fb_layout_t layout, const fb_transpose_t transa,
    const fb_transpose_t transb, const int m, const int n,
    const int k, const float alpha, const float *A, const int lda,
    const float *B, const int ldb, const float beta, float *C,
    const int ldc) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->sgemm_batch_strided) {
    return; /* Error: no batched GEMM implementation */
  }

  /* Call batched operation with batch_count=1 and zero strides */
  vtable->sgemm_batch_strided(layout, transa, transb, m, n, k, alpha, A, lda,
                              0,               /* strideA=0 */
                              B, ldb, 0,       /* strideB=0 */
                              beta, C, ldc, 0, /* strideC=0 */
                              1                /* batch_count=1 */
  );
}

/* ============================================================================
 * GEMM Single from Batched (Strided): DGEMM
 * ========================================================================= */

void fb_dgemm_from_dgemm_batch_strided(
    const fb_layout_t layout, const fb_transpose_t transa,
    const fb_transpose_t transb, const int m, const int n,
    const int k, const double alpha, const double *A, const int lda,
    const double *B, const int ldb, const double beta, double *C,
    const int ldc) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->dgemm_batch_strided) {
    return;
  }

  vtable->dgemm_batch_strided(layout, transa, transb, m, n, k, alpha, A, lda, 0,
                              B, ldb, 0, beta, C, ldc, 0, 1);
}

/* ============================================================================
 * GEMM Single from Batched (Strided): CGEMM
 * ========================================================================= */

void fb_cgemm_from_cgemm_batch_strided(
    const fb_layout_t layout, const fb_transpose_t transa,
    const fb_transpose_t transb, const int m, const int n,
    const int k, const fb_complex_float_t alpha,
    const fb_complex_float_t *A, const int lda, const fb_complex_float_t *B,
    const int ldb, const fb_complex_float_t beta, fb_complex_float_t *C,
    const int ldc) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->cgemm_batch_strided) {
    return;
  }

  vtable->cgemm_batch_strided(layout, transa, transb, m, n, k, alpha, A, lda, 0,
                              B, ldb, 0, beta, C, ldc, 0, 1);
}

/* ============================================================================
 * GEMM Single from Batched (Strided): ZGEMM
 * ========================================================================= */

void fb_zgemm_from_zgemm_batch_strided(
    const fb_layout_t layout, const fb_transpose_t transa,
    const fb_transpose_t transb, const int m, const int n,
    const int k, const fb_complex_double_t alpha,
    const fb_complex_double_t *A, const int lda,
    const fb_complex_double_t *B, const int ldb,
    const fb_complex_double_t beta, fb_complex_double_t *C, const int ldc) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->zgemm_batch_strided) {
    return;
  }

  vtable->zgemm_batch_strided(layout, transa, transb, m, n, k, alpha, A, lda, 0,
                              B, ldb, 0, beta, C, ldc, 0, 1);
}

/* ============================================================================
 * BLAS Level 1: SAXPY from Batched
 * ========================================================================= */

void fb_saxpy_from_saxpy_batch(int n, float alpha, const float *x, int incx,
                               float *y, int incy) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->saxpy_batch) {
    return;
  }

  /* Construct single-item array of pointers */
  const float **x_array =
      (const float **)fb_allocate_temp_buffer(sizeof(float *));
  float **y_array = (float **)fb_allocate_temp_buffer(sizeof(float *));

  if (!x_array || !y_array) {
    fb_free_temp_buffer(x_array);
    fb_free_temp_buffer(y_array);
    return; /* Out of memory */
  }

  x_array[0] = x;
  y_array[0] = y;

  vtable->saxpy_batch(1, &alpha, x_array, incx, y_array, incy, 1);

  fb_free_temp_buffer(x_array);
  fb_free_temp_buffer(y_array);
}

/* ============================================================================
 * BLAS Level 1: DAXPY from Batched
 * ========================================================================= */

void fb_daxpy_from_daxpy_batch(int n, double alpha, const double *x, int incx,
                               double *y, int incy) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->daxpy_batch) {
    return;
  }

  const double **x_array =
      (const double **)fb_allocate_temp_buffer(sizeof(double *));
  double **y_array = (double **)fb_allocate_temp_buffer(sizeof(double *));

  if (!x_array || !y_array) {
    fb_free_temp_buffer(x_array);
    fb_free_temp_buffer(y_array);
    return;
  }

  x_array[0] = x;
  y_array[0] = y;

  vtable->daxpy_batch(1, &alpha, x_array, incx, y_array, incy, 1);

  fb_free_temp_buffer(x_array);
  fb_free_temp_buffer(y_array);
}

/* ============================================================================
 * BLAS Level 2: SGEMV from Batched
 * ========================================================================= */

void fb_sgemv_from_sgemv_batch_strided(const fb_layout_t layout,
                                       const fb_transpose_t trans,
                                       const int m, const int n,
                                       const float alpha, const float *A,
                                       const int lda, const float *x,
                                       const int incx, const float beta,
                                       float *y, const int incy) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->sgemv_batch_strided) {
    return;
  }

  vtable->sgemv_batch_strided(layout, trans, m, n, alpha, A, lda, 0, x, incx, 0,
                              beta, y, incy, 0, 1);
}

/* ============================================================================
 * BLAS Level 2: DGEMV from Batched
 * ========================================================================= */

void fb_dgemv_from_dgemv_batch_strided(const fb_layout_t layout,
                                       const fb_transpose_t trans,
                                       const int m, const int n,
                                       const double alpha, const double *A,
                                       const int lda, const double *x,
                                       const int incx, const double beta,
                                       double *y, const int incy) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->dgemv_batch_strided) {
    return;
  }

  vtable->dgemv_batch_strided(layout, trans, m, n, alpha, A, lda, 0, x, incx, 0,
                              beta, y, incy, 0, 1);
}

/* ============================================================================
 * Installer Function: GEMM Strided Batched → Single
 * ========================================================================= */

/**
 * @brief Install single GEMM wrappers from strided batched operations
 *
 * If backend provides sgemm_batch_strided but not sgemm, generate sgemm
 * as a wrapper that calls sgemm_batch_strided with batch_count=1.
 * Same for dgemm, cgemm, zgemm.
 *
 * @param vtable Vtable to fill with missing single GEMM wrappers
 */
void fb_autofill_gemm_from_gemm_batch_strided(fb_backend_vtable_t *vtable) {
  if (!vtable) {
    return;
  }

  /* SGEMM */
  if (vtable->sgemm == NULL && vtable->sgemm_batch_strided != NULL) {
    vtable->sgemm = fb_sgemm_from_sgemm_batch_strided;
  }

  /* DGEMM */
  if (vtable->dgemm == NULL && vtable->dgemm_batch_strided != NULL) {
    vtable->dgemm = fb_dgemm_from_dgemm_batch_strided;
  }

  /* CGEMM */
  if (vtable->cgemm == NULL && vtable->cgemm_batch_strided != NULL) {
    vtable->cgemm = fb_cgemm_from_cgemm_batch_strided;
  }

  /* ZGEMM */
  if (vtable->zgemm == NULL && vtable->zgemm_batch_strided != NULL) {
    vtable->zgemm = fb_zgemm_from_zgemm_batch_strided;
  }
}

/* ============================================================================
 * Installer Function: BLAS L1 Batched Array → Single
 * ========================================================================= */

void fb_autofill_blas_l1_from_blas_l1_batch(fb_backend_vtable_t *vtable) {
  if (!vtable) {
    return;
  }

  /* SAXPY */
  if (vtable->saxpy == NULL && vtable->saxpy_batch != NULL) {
    vtable->saxpy = fb_saxpy_from_saxpy_batch;
  }

  /* DAXPY */
  if (vtable->daxpy == NULL && vtable->daxpy_batch != NULL) {
    vtable->daxpy = fb_daxpy_from_daxpy_batch;
  }
}

/* ============================================================================
 * Installer Function: BLAS L2 Strided Batched → Single
 * ========================================================================= */

void fb_autofill_gemv_from_gemv_batch_strided(fb_backend_vtable_t *vtable) {
  if (!vtable) {
    return;
  }

  /* SGEMV */
  if (vtable->sgemv == NULL && vtable->sgemv_batch_strided != NULL) {
    vtable->sgemv = fb_sgemv_from_sgemv_batch_strided;
  }

  /* DGEMV */
  if (vtable->dgemv == NULL && vtable->dgemv_batch_strided != NULL) {
    vtable->dgemv = fb_dgemv_from_dgemv_batch_strided;
  }
}

/* ============================================================================
 * Master Installer
 * ========================================================================= */

/**
 * @brief Install all single-operation wrappers from batched operations
 *
 * Called by fb_autofill_batched_to_single() in Strategy 2.
 * Checks each single-operation vtable entry; if NULL but corresponding
 * batched operation exists, installs the wrapper.
 *
 * @param vtable Vtable to fill
 */
void fb_autofill_all_from_batched(fb_backend_vtable_t *vtable) {
  if (!vtable) {
    return;
  }

  fb_autofill_gemm_from_gemm_batch_strided(vtable);
  fb_autofill_blas_l1_from_blas_l1_batch(vtable);
  fb_autofill_gemv_from_gemv_batch_strided(vtable);

  /* TODO: Phase 3.2 - Add more BLAS L1, L2, L3 operations */
  /* TODO: Phase 3.3 - Add normalization batched → single */
  /* TODO: Phase 3.4 - Add reduction batched → single */
}

#endif /* FB_EXTENDED_VTABLE_SUPPORT */
