/**
 * @file vtable_wrappers_gemm.c
 * @brief Auto-generated GEMM wrappers from unified operations
 *
 * This file contains wrappers that call gemm_unified() with appropriate
 * precision and mode flags. These enable backends that provide only
 * gemm_unified to work with traditional BLAS GEMM calls.
 *
 * Generated by Phase 2.1 of vtable auto-fill system.
 *
 * @copyright Copyright (c) 2025-2026
 * @license MIT OR Apache-2.0
 */

#include "../../include/faster-blaster/vtable_autofill.h"
#include "../backends/backend_interface.h"
#include <stddef.h>

/* ============================================================================
 * BLAS Level 3: GEMM Wrappers (Standard Single-Matrix Operations)
 * ========================================================================= */

/* SGEMM - Single precision matrix multiply */
void fb_sgemm_from_unified(const fb_layout_t layout,
                           const fb_transpose_t transa,
                           const fb_transpose_t transb, const int64_t m,
                           const int64_t n, const int64_t k, const float alpha,
                           const float *A, const int64_t lda, const float *B,
                           const int64_t ldb, const float beta, float *C,
                           const int64_t ldc) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->gemm_unified) {
    return; /* Error: no vtable or no unified implementation */
  }

  /* Convert layout to transpose characters for unified API */
  char trans_a = (transa == FB_NO_TRANS) ? 'N'
                 : (transa == FB_TRANS)  ? 'T'
                                         : 'C';
  char trans_b = (transb == FB_NO_TRANS) ? 'N'
                 : (transb == FB_TRANS)  ? 'T'
                                         : 'C';

  vtable->gemm_unified(FB_PREC_FP32,    /* precision */
                       FB_BATCH_SINGLE, /* batch_mode */
                       FB_FUSION_NONE,  /* fusion */
                       trans_a, trans_b, (size_t)m, (size_t)n, (size_t)k,
                       &alpha, A, (size_t)lda,
                       0,                 /* strideA=0 (not used for single) */
                       B, (size_t)ldb, 0, /* strideB=0 */
                       &beta, C, (size_t)ldc, 0, /* strideC=0 */
                       NULL,                     /* bias (no fusion) */
                       FB_ACT_NONE,              /* activation */
                       1,                        /* batch_count=1 */
                       NULL                      /* stream (default) */
  );
}

/* DGEMM - Double precision matrix multiply */
void fb_dgemm_from_unified(const fb_layout_t layout,
                           const fb_transpose_t transa,
                           const fb_transpose_t transb, const int64_t m,
                           const int64_t n, const int64_t k, const double alpha,
                           const double *A, const int64_t lda, const double *B,
                           const int64_t ldb, const double beta, double *C,
                           const int64_t ldc) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->gemm_unified) {
    return;
  }

  char trans_a = (transa == FB_NO_TRANS) ? 'N'
                 : (transa == FB_TRANS)  ? 'T'
                                         : 'C';
  char trans_b = (transb == FB_NO_TRANS) ? 'N'
                 : (transb == FB_TRANS)  ? 'T'
                                         : 'C';

  vtable->gemm_unified(FB_PREC_FP64, FB_BATCH_SINGLE, FB_FUSION_NONE, trans_a,
                       trans_b, (size_t)m, (size_t)n, (size_t)k, &alpha, A,
                       (size_t)lda, 0, B, (size_t)ldb, 0, &beta, C, (size_t)ldc,
                       0, NULL, FB_ACT_NONE, 1, NULL);
}

/* CGEMM - Complex single precision matrix multiply */
void fb_cgemm_from_unified(const fb_layout_t layout,
                           const fb_transpose_t transa,
                           const fb_transpose_t transb, const int64_t m,
                           const int64_t n, const int64_t k,
                           const fb_complex_float_t alpha,
                           const fb_complex_float_t *A, const int64_t lda,
                           const fb_complex_float_t *B, const int64_t ldb,
                           const fb_complex_float_t beta, fb_complex_float_t *C,
                           const int64_t ldc) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->gemm_unified) {
    return;
  }

  char trans_a = (transa == FB_NO_TRANS) ? 'N'
                 : (transa == FB_TRANS)  ? 'T'
                                         : 'C';
  char trans_b = (transb == FB_NO_TRANS) ? 'N'
                 : (transb == FB_TRANS)  ? 'T'
                                         : 'C';

  vtable->gemm_unified(FB_PREC_C64, FB_BATCH_SINGLE, FB_FUSION_NONE, trans_a,
                       trans_b, (size_t)m, (size_t)n, (size_t)k, &alpha, A,
                       (size_t)lda, 0, B, (size_t)ldb, 0, &beta, C, (size_t)ldc,
                       0, NULL, FB_ACT_NONE, 1, NULL);
}

/* ZGEMM - Complex double precision matrix multiply */
void fb_zgemm_from_unified(const fb_layout_t layout,
                           const fb_transpose_t transa,
                           const fb_transpose_t transb, const int64_t m,
                           const int64_t n, const int64_t k,
                           const fb_complex_double_t alpha,
                           const fb_complex_double_t *A, const int64_t lda,
                           const fb_complex_double_t *B, const int64_t ldb,
                           const fb_complex_double_t beta,
                           fb_complex_double_t *C, const int64_t ldc) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->gemm_unified) {
    return;
  }

  char trans_a = (transa == FB_NO_TRANS) ? 'N'
                 : (transa == FB_TRANS)  ? 'T'
                                         : 'C';
  char trans_b = (transb == FB_NO_TRANS) ? 'N'
                 : (transb == FB_TRANS)  ? 'T'
                                         : 'C';

  vtable->gemm_unified(FB_PREC_C128, FB_BATCH_SINGLE, FB_FUSION_NONE, trans_a,
                       trans_b, (size_t)m, (size_t)n, (size_t)k, &alpha, A,
                       (size_t)lda, 0, B, (size_t)ldb, 0, &beta, C, (size_t)ldc,
                       0, NULL, FB_ACT_NONE, 1, NULL);
}

/* ============================================================================
 * Vtable Auto-Fill Function: Install GEMM Wrappers
 * ========================================================================= */

/**
 * @brief Fill missing GEMM entries in vtable from gemm_unified
 *
 * Called by fb_autofill_unified_to_specific() during plugin finalization.
 * Only installs wrappers for missing operations - doesn't overwrite existing
 * ones.
 */
void fb_autofill_gemm_from_unified(fb_backend_vtable_t *vtable) {
  if (!vtable || !vtable->gemm_unified) {
    return; /* No unified implementation available */
  }

  /* Install wrappers only if specific operations are missing */
  if (vtable->sgemm == NULL) {
    vtable->sgemm = fb_sgemm_from_unified;
  }

  if (vtable->dgemm == NULL) {
    vtable->dgemm = fb_dgemm_from_unified;
  }

  if (vtable->cgemm == NULL) {
    vtable->cgemm = fb_cgemm_from_unified;
  }

  if (vtable->zgemm == NULL) {
    vtable->zgemm = fb_zgemm_from_unified;
  }
}
