/**
 * @file vtable_wrappers_reduction.c
 * @brief Auto-generated reduction wrappers from unified operations
 *
 * This file contains wrappers that call reduce_unified() with appropriate
 * operation and scope flags. These enable backends that provide only
 * reduce_unified to work with specific reduction operation calls.
 *
 * Generated by Phase 2.3 of vtable auto-fill system.
 *
 * @copyright Copyright (c) 2025-2026
 * @license MIT OR Apache-2.0
 */

#include "../../include/faster-blaster/vtable_autofill.h"
#include "../backends/backend_interface.h"
#include <stddef.h>

/* These wrappers require extended vtable with reduce_unified operation.
 * Guard compilation until vtable is extended. */
#ifdef FB_EXTENDED_VTABLE_SUPPORT

/* ============================================================================
 * Tensor Reductions (Section 15.2)
 * ========================================================================= */

/* Tensor Reduce Sum */
void fb_tensor_reduce_sum_from_unified(const void *input, void *output,
                                       const size_t *dims, size_t ndims,
                                       const int *reduce_axes, size_t num_axes,
                                       int keep_dims) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->reduce_unified) {
    return; /* Error: no reduce_unified implementation */
  }

  vtable->reduce_unified(FB_REDUCE_SUM,          /* operation */
                         FB_REDUCE_LOCAL, /* scope */
                         input, output, dims, ndims, reduce_axes, num_axes,
                         keep_dims, NULL, 0, /* no workspace needed */
                         NULL                /* default stream */
  );
}

/* Tensor Reduce Max */
void fb_tensor_reduce_max_from_unified(const void *input, void *output,
                                       const size_t *dims, size_t ndims,
                                       const int *reduce_axes, size_t num_axes,
                                       int keep_dims) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->reduce_unified) {
    return;
  }

  vtable->reduce_unified(FB_REDUCE_MAX, FB_REDUCE_LOCAL, input, output,
                         dims, ndims, reduce_axes, num_axes, keep_dims, NULL, 0,
                         NULL);
}

/* Tensor Reduce Min */
void fb_tensor_reduce_min_from_unified(const void *input, void *output,
                                       const size_t *dims, size_t ndims,
                                       const int *reduce_axes, size_t num_axes,
                                       int keep_dims) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->reduce_unified) {
    return;
  }

  vtable->reduce_unified(FB_REDUCE_MIN, FB_REDUCE_LOCAL, input, output,
                         dims, ndims, reduce_axes, num_axes, keep_dims, NULL, 0,
                         NULL);
}

/* Tensor Reduce Mean */
void fb_tensor_reduce_mean_from_unified(const void *input, void *output,
                                        const size_t *dims, size_t ndims,
                                        const int *reduce_axes, size_t num_axes,
                                        int keep_dims) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->reduce_unified) {
    return;
  }

  vtable->reduce_unified(FB_REDUCE_MEAN, FB_REDUCE_LOCAL, input, output,
                         dims, ndims, reduce_axes, num_axes, keep_dims, NULL, 0,
                         NULL);
}

/* Tensor Reduce L1 Norm */
void fb_tensor_reduce_norm_l1_from_unified(const void *input, void *output,
                                           const size_t *dims, size_t ndims,
                                           const int *reduce_axes,
                                           size_t num_axes, int keep_dims) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->reduce_unified) {
    return;
  }

  vtable->reduce_unified(FB_REDUCE_NORM_L1, FB_REDUCE_LOCAL, input,
                         output, dims, ndims, reduce_axes, num_axes, keep_dims,
                         NULL, 0, NULL);
}

/* Tensor Reduce L2 Norm */
void fb_tensor_reduce_norm_l2_from_unified(const void *input, void *output,
                                           const size_t *dims, size_t ndims,
                                           const int *reduce_axes,
                                           size_t num_axes, int keep_dims) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->reduce_unified) {
    return;
  }

  vtable->reduce_unified(FB_REDUCE_NORM_L2, FB_REDUCE_LOCAL, input,
                         output, dims, ndims, reduce_axes, num_axes, keep_dims,
                         NULL, 0, NULL);
}

/* ============================================================================
 * Parallel Primitives: Local Reductions (Section 14.3)
 * ========================================================================= */

/* Parallel Reduce Sum */
void fb_prim_reduce_sum_from_unified(const void *input, void *output,
                                     size_t count) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->reduce_unified) {
    return;
  }

  /* Use 1D tensor reduction */
  size_t dims[1] = {count};
  int reduce_axes[1] = {0};

  vtable->reduce_unified(FB_REDUCE_SUM, FB_REDUCE_LOCAL, input, output,
                         dims, 1, reduce_axes, 1, 0, /* don't keep dims */
                         NULL, 0, NULL);
}

/* Parallel Reduce Max */
void fb_prim_reduce_max_from_unified(const void *input, void *output,
                                     size_t count) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->reduce_unified) {
    return;
  }

  size_t dims[1] = {count};
  int reduce_axes[1] = {0};

  vtable->reduce_unified(FB_REDUCE_MAX, FB_REDUCE_LOCAL, input, output,
                         dims, 1, reduce_axes, 1, 0, NULL, 0, NULL);
}

/* Parallel Reduce Min */
void fb_prim_reduce_min_from_unified(const void *input, void *output,
                                     size_t count) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->reduce_unified) {
    return;
  }

  size_t dims[1] = {count};
  int reduce_axes[1] = {0};

  vtable->reduce_unified(FB_REDUCE_MIN, FB_REDUCE_LOCAL, input, output,
                         dims, 1, reduce_axes, 1, 0, NULL, 0, NULL);
}

/* Parallel Reduce Product */
void fb_prim_reduce_product_from_unified(const void *input, void *output,
                                         size_t count) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->reduce_unified) {
    return;
  }

  size_t dims[1] = {count};
  int reduce_axes[1] = {0};

  vtable->reduce_unified(FB_REDUCE_PRODUCT, FB_REDUCE_LOCAL, input,
                         output, dims, 1, reduce_axes, 1, 0, NULL, 0, NULL);
}

/* ============================================================================
 * Parallel Primitives: Scan Operations (Section 14.4)
 * ========================================================================= */

/* Inclusive Scan Sum */
void fb_prim_scan_sum_inclusive_from_unified(const void *input, void *output,
                                             size_t count) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->reduce_unified) {
    return;
  }

  size_t dims[1] = {count};
  int reduce_axes[1] = {0};

  vtable->reduce_unified(FB_REDUCE_SUM, FB_REDUCE_LOCAL, input, output,
                         dims, 1, reduce_axes, 1,
                         1, /* keep_dims for scan semantics */
                         NULL, 0, NULL);
}

/* Exclusive Scan Sum */
void fb_prim_scan_sum_exclusive_from_unified(const void *input, void *output,
                                             size_t count) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->reduce_unified) {
    return;
  }

  size_t dims[1] = {count};
  int reduce_axes[1] = {0};

  vtable->reduce_unified(FB_REDUCE_SUM, FB_REDUCE_LOCAL, input, output,
                         dims, 1, reduce_axes, 1, 1, NULL, 0, NULL);
}

/* Inclusive Scan Max */
void fb_prim_scan_max_inclusive_from_unified(const void *input, void *output,
                                             size_t count) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->reduce_unified) {
    return;
  }

  size_t dims[1] = {count};
  int reduce_axes[1] = {0};

  vtable->reduce_unified(FB_REDUCE_MAX, FB_REDUCE_LOCAL, input, output,
                         dims, 1, reduce_axes, 1, 1, NULL, 0, NULL);
}

/* Exclusive Scan Max */
void fb_prim_scan_max_exclusive_from_unified(const void *input, void *output,
                                             size_t count) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->reduce_unified) {
    return;
  }

  size_t dims[1] = {count};
  int reduce_axes[1] = {0};

  vtable->reduce_unified(FB_REDUCE_MAX, FB_REDUCE_LOCAL, input, output,
                         dims, 1, reduce_axes, 1, 1, NULL, 0, NULL);
}

/* Inclusive Scan Min */
void fb_prim_scan_min_inclusive_from_unified(const void *input, void *output,
                                             size_t count) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->reduce_unified) {
    return;
  }

  size_t dims[1] = {count};
  int reduce_axes[1] = {0};

  vtable->reduce_unified(FB_REDUCE_MIN, FB_REDUCE_LOCAL, input, output,
                         dims, 1, reduce_axes, 1, 1, NULL, 0, NULL);
}

/* Exclusive Scan Min */
void fb_prim_scan_min_exclusive_from_unified(const void *input, void *output,
                                             size_t count) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->reduce_unified) {
    return;
  }

  size_t dims[1] = {count};
  int reduce_axes[1] = {0};

  vtable->reduce_unified(FB_REDUCE_MIN, FB_REDUCE_LOCAL, input, output,
                         dims, 1, reduce_axes, 1, 1, NULL, 0, NULL);
}

/* Inclusive Scan Product */
void fb_prim_scan_product_inclusive_from_unified(const void *input,
                                                 void *output, size_t count) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->reduce_unified) {
    return;
  }

  size_t dims[1] = {count};
  int reduce_axes[1] = {0};

  vtable->reduce_unified(FB_REDUCE_PRODUCT, FB_REDUCE_LOCAL, input,
                         output, dims, 1, reduce_axes, 1, 1, NULL, 0, NULL);
}

/* Exclusive Scan Product */
void fb_prim_scan_product_exclusive_from_unified(const void *input,
                                                 void *output, size_t count) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->reduce_unified) {
    return;
  }

  size_t dims[1] = {count};
  int reduce_axes[1] = {0};

  vtable->reduce_unified(FB_REDUCE_PRODUCT, FB_REDUCE_LOCAL, input,
                         output, dims, 1, reduce_axes, 1, 1, NULL, 0, NULL);
}

/* ============================================================================
 * Statistics: Reductions (Section 10.2)
 * ========================================================================= */

/* Statistical Sum */
void fb_stats_sum_from_unified(const void *data, size_t n, void *result) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->reduce_unified) {
    return;
  }

  size_t dims[1] = {n};
  int reduce_axes[1] = {0};

  vtable->reduce_unified(FB_REDUCE_SUM, FB_REDUCE_LOCAL, data, result,
                         dims, 1, reduce_axes, 1, 0, NULL, 0, NULL);
}

/* Statistical Mean */
void fb_stats_mean_from_unified(const void *data, size_t n, void *result) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->reduce_unified) {
    return;
  }

  size_t dims[1] = {n};
  int reduce_axes[1] = {0};

  vtable->reduce_unified(FB_REDUCE_MEAN, FB_REDUCE_LOCAL, data, result,
                         dims, 1, reduce_axes, 1, 0, NULL, 0, NULL);
}

/* Statistical Variance */
void fb_stats_variance_from_unified(const void *data, size_t n, void *result) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->reduce_unified) {
    return;
  }

  size_t dims[1] = {n};
  int reduce_axes[1] = {0};

  vtable->reduce_unified(FB_REDUCE_VARIANCE, FB_REDUCE_LOCAL, data,
                         result, dims, 1, reduce_axes, 1, 0, NULL, 0, NULL);
}

/* Statistical Standard Deviation */
void fb_stats_std_dev_from_unified(const void *data, size_t n, void *result) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->reduce_unified) {
    return;
  }

  size_t dims[1] = {n};
  int reduce_axes[1] = {0};

  vtable->reduce_unified(FB_REDUCE_STD_DEV, FB_REDUCE_LOCAL, data, result,
                         dims, 1, reduce_axes, 1, 0, NULL, 0, NULL);
}

/* ============================================================================
 * Collective Communication: Reductions (Section 12)
 * ========================================================================= */

/* NCCL AllReduce */
void fb_nccl_allreduce_from_unified(const void *send_buf, void *recv_buf,
                                    size_t count, fb_reduce_op_t op,
                                    void *comm) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->reduce_unified) {
    return;
  }

  size_t dims[1] = {count};
  int reduce_axes[1] = {0};

  vtable->reduce_unified(op, FB_REDUCE_COLLECTIVE, send_buf, recv_buf,
                         dims, 1, reduce_axes, 1, 0, NULL, 0,
                         comm /* pass communicator as stream parameter */
  );
}

/* NCCL Reduce */
void fb_nccl_reduce_from_unified(const void *send_buf, void *recv_buf,
                                 size_t count, fb_reduce_op_t op, int root,
                                 void *comm) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->reduce_unified) {
    return;
  }

  size_t dims[1] = {count};
  int reduce_axes[1] = {root}; /* use reduce_axes to pass root rank */

  vtable->reduce_unified(op, FB_REDUCE_COLLECTIVE, send_buf, recv_buf,
                         dims, 1, reduce_axes, 1, 0, NULL, 0, comm);
}

/* NCCL ReduceScatter */
void fb_nccl_reduce_scatter_from_unified(const void *send_buf, void *recv_buf,
                                         size_t recv_count, fb_reduce_op_t op,
                                         void *comm) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->reduce_unified) {
    return;
  }

  size_t dims[1] = {recv_count};
  int reduce_axes[1] = {0};

  vtable->reduce_unified(op, FB_REDUCE_COLLECTIVE, send_buf, recv_buf,
                         dims, 1, reduce_axes, 1, 0, NULL, 0, comm);
}

/* ============================================================================
 * Installer Function
 * ========================================================================= */

/**
 * @brief Install all reduction wrappers from reduce_unified
 *
 * This function checks each vtable entry for reduction operations.
 * If the entry is NULL but reduce_unified exists, it installs the wrapper.
 * This is called by fb_autofill_unified_to_specific() in Strategy 1.
 *
 * @param vtable Vtable to fill with missing reduction wrappers
 */
void fb_autofill_reduction_from_unified(fb_backend_vtable_t *vtable) {
  if (!vtable || !vtable->reduce_unified) {
    return; /* No unified implementation available */
  }

  /* Tensor Reductions */
  if (vtable->tensor_reduce_sum == NULL) {
    vtable->tensor_reduce_sum = fb_tensor_reduce_sum_from_unified;
  }
  if (vtable->tensor_reduce_max == NULL) {
    vtable->tensor_reduce_max = fb_tensor_reduce_max_from_unified;
  }
  if (vtable->tensor_reduce_min == NULL) {
    vtable->tensor_reduce_min = fb_tensor_reduce_min_from_unified;
  }
  if (vtable->tensor_reduce_mean == NULL) {
    vtable->tensor_reduce_mean = fb_tensor_reduce_mean_from_unified;
  }
  if (vtable->tensor_reduce_norm_l1 == NULL) {
    vtable->tensor_reduce_norm_l1 = fb_tensor_reduce_norm_l1_from_unified;
  }
  if (vtable->tensor_reduce_norm_l2 == NULL) {
    vtable->tensor_reduce_norm_l2 = fb_tensor_reduce_norm_l2_from_unified;
  }

  /* Parallel Primitive Reductions */
  if (vtable->prim_reduce_sum == NULL) {
    vtable->prim_reduce_sum = fb_prim_reduce_sum_from_unified;
  }
  if (vtable->prim_reduce_max == NULL) {
    vtable->prim_reduce_max = fb_prim_reduce_max_from_unified;
  }
  if (vtable->prim_reduce_min == NULL) {
    vtable->prim_reduce_min = fb_prim_reduce_min_from_unified;
  }
  if (vtable->prim_reduce_product == NULL) {
    vtable->prim_reduce_product = fb_prim_reduce_product_from_unified;
  }

  /* Scan Operations */
  if (vtable->prim_scan_sum_inclusive == NULL) {
    vtable->prim_scan_sum_inclusive = fb_prim_scan_sum_inclusive_from_unified;
  }
  if (vtable->prim_scan_sum_exclusive == NULL) {
    vtable->prim_scan_sum_exclusive = fb_prim_scan_sum_exclusive_from_unified;
  }
  if (vtable->prim_scan_max_inclusive == NULL) {
    vtable->prim_scan_max_inclusive = fb_prim_scan_max_inclusive_from_unified;
  }
  if (vtable->prim_scan_max_exclusive == NULL) {
    vtable->prim_scan_max_exclusive = fb_prim_scan_max_exclusive_from_unified;
  }
  if (vtable->prim_scan_min_inclusive == NULL) {
    vtable->prim_scan_min_inclusive = fb_prim_scan_min_inclusive_from_unified;
  }
  if (vtable->prim_scan_min_exclusive == NULL) {
    vtable->prim_scan_min_exclusive = fb_prim_scan_min_exclusive_from_unified;
  }
  if (vtable->prim_scan_product_inclusive == NULL) {
    vtable->prim_scan_product_inclusive =
        fb_prim_scan_product_inclusive_from_unified;
  }
  if (vtable->prim_scan_product_exclusive == NULL) {
    vtable->prim_scan_product_exclusive =
        fb_prim_scan_product_exclusive_from_unified;
  }

  /* Statistical Reductions */
  if (vtable->stats_sum == NULL) {
    vtable->stats_sum = fb_stats_sum_from_unified;
  }
  if (vtable->stats_mean == NULL) {
    vtable->stats_mean = fb_stats_mean_from_unified;
  }
  if (vtable->stats_variance == NULL) {
    vtable->stats_variance = fb_stats_variance_from_unified;
  }
  if (vtable->stats_std_dev == NULL) {
    vtable->stats_std_dev = fb_stats_std_dev_from_unified;
  }

  /* Collective Communication Reductions */
  if (vtable->nccl_allreduce == NULL) {
    vtable->nccl_allreduce = fb_nccl_allreduce_from_unified;
  }
  if (vtable->nccl_reduce == NULL) {
    vtable->nccl_reduce = fb_nccl_reduce_from_unified;
  }
  if (vtable->nccl_reduce_scatter == NULL) {
    vtable->nccl_reduce_scatter = fb_nccl_reduce_scatter_from_unified;
  }
}

#endif /* FB_EXTENDED_VTABLE_SUPPORT */

