/**
 * @file vtable_wrappers_normalization.c
 * @brief Auto-generated normalization wrappers from unified operations
 *
 * This file contains wrappers that call normalize_unified() with appropriate
 * mode and phase flags. These enable backends that provide only
 * normalize_unified to work with specific normalization operation calls.
 *
 * Generated by Phase 2.2 of vtable auto-fill system.
 *
 * @copyright Copyright (c) 2025-2026
 * @license MIT OR Apache-2.0
 */

#include "../../include/faster-blaster/vtable_autofill.h"
#include "../backends/backend_interface.h"
#include <stddef.h>

/* These wrappers require extended vtable with normalize_unified operation.
 * Guard compilation until vtable is extended. */
#ifdef FB_EXTENDED_VTABLE_SUPPORT

/* ============================================================================
 * DNN Primitives: Batch Normalization Wrappers (Section 13.4)
 * ========================================================================= */

/* Batch Normalization - Training Forward Pass */
void fb_batch_norm_forward_training_from_unified(
    const size_t *dims, size_t ndims, const void *input, void *output,
    const void *scale, const void *bias, void *running_mean, void *running_var,
    float momentum, float epsilon) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->normalize_unified) {
    return;
  }

  vtable->normalize_unified(
      FB_NORM_BATCH,        /* mode */
      FB_NORM_TRAINING,     /* phase */
      dims, ndims, NULL, 0, /* normalize_axes (auto-selected for batch norm) */
      input, output, scale, bias, running_mean, running_var, momentum, epsilon,
      0,                     /* num_groups (not used for batch norm) */
      0.0f, 1.0f,            /* scale_min, scale_max (not used) */
      NULL, NULL, NULL, NULL /* gradients (not used in forward pass) */
  );
}

/* Batch Normalization - Inference Forward Pass */
void fb_batch_norm_forward_inference_from_unified(
    const size_t *dims, size_t ndims, const void *input, void *output,
    const void *scale, const void *bias, const void *running_mean,
    const void *running_var, float epsilon) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->normalize_unified) {
    return;
  }

  vtable->normalize_unified(
      FB_NORM_BATCH, FB_NORM_INFERENCE, /* inference mode */
      dims, ndims, NULL, 0, input, output, scale, bias, running_mean,
      running_var, 0.0f, epsilon, /* momentum not used in inference */
      0, 0.0f, 1.0f, NULL, NULL, NULL, NULL);
}

/* Batch Normalization - Backward Pass */
void fb_batch_norm_backward_from_unified(
    const size_t *dims, size_t ndims, const void *input,
    const void *grad_output, void *grad_input, void *grad_scale,
    void *grad_bias, const void *scale, const void *running_mean,
    const void *running_var, float epsilon) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->normalize_unified) {
    return;
  }

  vtable->normalize_unified(
      FB_NORM_BATCH, FB_NORM_TRAINING,   /* backward pass uses training mode */
      dims, ndims, NULL, 0, input, NULL, /* output not needed for backward */
      scale, NULL,                       /* bias not needed for backward */
      running_mean, running_var, 0.0f, epsilon, 0, 0.0f, 1.0f, grad_output,
      grad_input, grad_scale, grad_bias);
}

/* Layer Normalization - Forward Pass */
void fb_layer_norm_forward_from_unified(const size_t *dims, size_t ndims,
                                        const void *input, void *output,
                                        const void *scale, const void *bias,
                                        float epsilon) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->normalize_unified) {
    return;
  }

  vtable->normalize_unified(
      FB_NORM_LAYER,
      FB_NORM_TRAINING,     /* layer norm doesn't distinguish train/inference */
      dims, ndims, NULL, 0, /* normalize over last dimension(s) by default */
      input, output, scale, bias, NULL, NULL, /* no running statistics */
      0.0f, epsilon, 0, 0.0f, 1.0f, NULL, NULL, NULL, NULL);
}

/* Layer Normalization - Backward Pass */
void fb_layer_norm_backward_from_unified(const size_t *dims, size_t ndims,
                                         const void *input,
                                         const void *grad_output,
                                         void *grad_input, void *grad_scale,
                                         void *grad_bias, const void *scale,
                                         float epsilon) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->normalize_unified) {
    return;
  }

  vtable->normalize_unified(FB_NORM_LAYER, FB_NORM_TRAINING, dims, ndims, NULL,
                            0, input, NULL, scale, NULL, NULL, NULL, 0.0f,
                            epsilon, 0, 0.0f, 1.0f, grad_output, grad_input,
                            grad_scale, grad_bias);
}

/* Instance Normalization - Forward Pass */
void fb_instance_norm_forward_from_unified(const size_t *dims, size_t ndims,
                                           const void *input, void *output,
                                           const void *scale, const void *bias,
                                           float epsilon) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->normalize_unified) {
    return;
  }

  vtable->normalize_unified(FB_NORM_INSTANCE, FB_NORM_TRAINING, dims, ndims,
                            NULL,
                            0, /* normalize spatial dims per sample/channel */
                            input, output, scale, bias, NULL, NULL, 0.0f,
                            epsilon, 0, 0.0f, 1.0f, NULL, NULL, NULL, NULL);
}

/* Group Normalization - Forward Pass */
void fb_group_norm_forward_from_unified(const size_t *dims, size_t ndims,
                                        const void *input, void *output,
                                        const void *scale, const void *bias,
                                        int num_groups, float epsilon) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->normalize_unified) {
    return;
  }

  vtable->normalize_unified(FB_NORM_GROUP, FB_NORM_TRAINING, dims, ndims, NULL,
                            0, input, output, scale, bias, NULL, NULL, 0.0f,
                            epsilon,
                            num_groups, /* key parameter for group norm */
                            0.0f, 1.0f, NULL, NULL, NULL, NULL);
}

/* ============================================================================
 * Statistics: Z-Score Normalization Wrappers (Section 14)
 * ========================================================================= */

/* Standard Z-Score Normalization */
void fb_stats_zscore_from_unified(const void *input, void *output,
                                  size_t count) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->normalize_unified) {
    return;
  }

  size_t dims[1] = {count};

  vtable->normalize_unified(
      FB_NORM_Z_SCORE, FB_NORM_TRAINING, dims, 1, NULL, 0, input, output, NULL,
      NULL,                    /* no scale/bias parameters */
      NULL, NULL, 0.0f, 1e-8f, /* small epsilon for numerical stability */
      0, 0.0f, 1.0f, NULL, NULL, NULL, NULL);
}

/* Modified Z-Score (robust to outliers) */
void fb_stats_modified_zscore_from_unified(const void *input, void *output,
                                           size_t count) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->normalize_unified) {
    return;
  }

  size_t dims[1] = {count};

  /* Modified z-score uses median absolute deviation instead of std dev
   * For now, we route to standard z-score; backends can override
   * with specialized implementation if needed */
  vtable->normalize_unified(
      FB_NORM_Z_SCORE, /* use standard z-score as approximation */
      FB_NORM_TRAINING, dims, 1, NULL, 0, input, output, NULL, NULL, NULL, NULL,
      0.0f, 1e-8f, 0, 0.0f, 1.0f, NULL, NULL, NULL, NULL);
}

/* ============================================================================
 * Preprocessing: Data Normalization Wrappers (Section 15.5)
 * ========================================================================= */

/* Standardize (z-score normalization, alias) */
void fb_standardize_from_unified(const void *input, void *output,
                                 size_t count) {

  /* Standardize is identical to z-score */
  fb_stats_zscore_from_unified(input, output, count);
}

/* Normalize (L1/L2/Max normalization) */
void fb_normalize_from_unified(const void *input, void *output, size_t count,
                               int norm_type) { /* 1=L1, 2=L2, 0=Max */

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->normalize_unified) {
    return;
  }

  size_t dims[1] = {count};

  /* Map norm_type to mode enum */
  fb_norm_mode_t mode;
  switch (norm_type) {
  case 1:
    mode = FB_NORM_L1;
    break;
  case 2:
    mode = FB_NORM_L2;
    break;
  default:
    mode = FB_NORM_MAX;
    break;
  }

  vtable->normalize_unified(mode, FB_NORM_TRAINING, dims, 1, NULL, 0, input,
                            output, NULL, NULL, NULL, NULL, 0.0f, 1e-8f, 0,
                            0.0f, 1.0f, NULL, NULL, NULL, NULL);
}

/* Min-Max Scaling */
void fb_min_max_scale_from_unified(const void *input, void *output,
                                   size_t count, float scale_min,
                                   float scale_max) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->normalize_unified) {
    return;
  }

  size_t dims[1] = {count};

  vtable->normalize_unified(FB_NORM_MIN_MAX_SCALE, FB_NORM_TRAINING, dims, 1,
                            NULL, 0, input, output, NULL, NULL, NULL, NULL,
                            0.0f, 1e-8f, 0, scale_min,
                            scale_max, /* target range */
                            NULL, NULL, NULL, NULL);
}

/* ============================================================================
 * Vtable Auto-Fill Function: Install Normalization Wrappers
 * ========================================================================= */

/**
 * @brief Fill missing normalization entries in vtable from normalize_unified
 *
 * Called by fb_autofill_unified_to_specific() during plugin finalization.
 * Only installs wrappers for missing operations - doesn't overwrite existing
 * ones.
 */
void fb_autofill_normalization_from_unified(fb_backend_vtable_t *vtable) {
  if (!vtable || !vtable->normalize_unified) {
    return; /* No unified implementation available */
  }

  /* DNN Primitives - Batch Normalization */
  if (vtable->batch_norm_forward_training == NULL) {
    vtable->batch_norm_forward_training =
        fb_batch_norm_forward_training_from_unified;
  }
  if (vtable->batch_norm_forward_inference == NULL) {
    vtable->batch_norm_forward_inference =
        fb_batch_norm_forward_inference_from_unified;
  }
  if (vtable->batch_norm_backward == NULL) {
    vtable->batch_norm_backward = fb_batch_norm_backward_from_unified;
  }

  /* DNN Primitives - Layer Normalization */
  if (vtable->layer_norm_forward == NULL) {
    vtable->layer_norm_forward = fb_layer_norm_forward_from_unified;
  }
  if (vtable->layer_norm_backward == NULL) {
    vtable->layer_norm_backward = fb_layer_norm_backward_from_unified;
  }

  /* DNN Primitives - Instance/Group Normalization */
  if (vtable->instance_norm_forward == NULL) {
    vtable->instance_norm_forward = fb_instance_norm_forward_from_unified;
  }
  if (vtable->group_norm_forward == NULL) {
    vtable->group_norm_forward = fb_group_norm_forward_from_unified;
  }

  /* Statistics - Z-Score */
  if (vtable->stats_zscore == NULL) {
    vtable->stats_zscore = fb_stats_zscore_from_unified;
  }
  if (vtable->stats_modified_zscore == NULL) {
    vtable->stats_modified_zscore = fb_stats_modified_zscore_from_unified;
  }

  /* Preprocessing - Normalization Operations */
  if (vtable->standardize == NULL) {
    vtable->standardize = fb_standardize_from_unified;
  }
  if (vtable->normalize == NULL) {
    vtable->normalize = fb_normalize_from_unified;
  }
  if (vtable->min_max_scale == NULL) {
    vtable->min_max_scale = fb_min_max_scale_from_unified;
  }
}

#endif /* FB_EXTENDED_VTABLE_SUPPORT */