/**
 * @file vtable_wrappers_strided_to_array.c
 * @brief Auto-generated strided batching wrappers from array-based batched
 * operations
 *
 * This file contains wrappers that construct pointer arrays from strided
 * parameters and call array-based batched operations. These enable backends
 * that provide only array-based batching to work with strided batching calls.
 *
 * Generated by Phase 4 of vtable auto-fill system.
 *
 * @copyright Copyright (c) 2025-2026
 * @license MIT OR Apache-2.0
 */

#include "../../include/faster-blaster/vtable_autofill.h"
#include "../backends/backend_interface.h"
#include <stddef.h>
#include <stdlib.h>
#include <string.h>

/* ============================================================================
 * Helper: Construct pointer arrays from strided data
 * ========================================================================= */

/**
 * @brief Construct array of pointers from strided data
 *
 * Given a base pointer, element stride, and count, creates an array of
 * pointers pointing to each strided element.
 *
 * @param base_ptr Base pointer to data
 * @param stride Byte stride between elements
 * @param count Number of pointers to create
 * @return Allocated array of pointers (must be freed with fb_free_temp_buffer)
 */
static void **fb_construct_strided_ptr_array(const void *base_ptr,
                                             size_t stride, size_t count) {
  void **ptr_array = (void **)fb_allocate_temp_buffer(count * sizeof(void *));
  if (!ptr_array) {
    return NULL;
  }

  for (size_t i = 0; i < count; i++) {
    ptr_array[i] = (void *)((uintptr_t)base_ptr + i * stride);
  }

  return ptr_array;
}

/* ============================================================================
 * GEMM: Strided Batched from Array Batched (SGEMM)
 * ========================================================================= */

void fb_sgemm_batch_strided_from_sgemm_batch(
    const fb_layout_t layout, const fb_transpose_t transa,
    const fb_transpose_t transb, const int64_t m, const int64_t n,
    const int64_t k, const float alpha, const float *A, const int64_t lda,
    const int64_t strideA, const float *B, const int64_t ldb,
    const int64_t strideB, const float beta, float *C, const int64_t ldc,
    const int64_t strideC, const int64_t batch_count) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->sgemm_batch) {
    return;
  }

  /* Construct pointer arrays from strided data */
  const float **A_array =
      (const float **)fb_construct_strided_ptr_array(A, strideA, batch_count);
  const float **B_array =
      (const float **)fb_construct_strided_ptr_array(B, strideB, batch_count);
  float **C_array =
      (float **)fb_construct_strided_ptr_array(C, strideC, batch_count);

  if (!A_array || !B_array || !C_array) {
    /* Cleanup and return on allocation failure */
    fb_free_temp_buffer(A_array);
    fb_free_temp_buffer(B_array);
    fb_free_temp_buffer(C_array);
    return;
  }

  /* Call array-based operation */
  vtable->sgemm_batch(layout, transa, transb, m, n, k, alpha, A_array, lda,
                      B_array, ldb, beta, C_array, ldc, batch_count);

  /* Cleanup */
  fb_free_temp_buffer(A_array);
  fb_free_temp_buffer(B_array);
  fb_free_temp_buffer(C_array);
}

/* ============================================================================
 * GEMM: Strided Batched from Array Batched (DGEMM)
 * ========================================================================= */

void fb_dgemm_batch_strided_from_dgemm_batch(
    const fb_layout_t layout, const fb_transpose_t transa,
    const fb_transpose_t transb, const int64_t m, const int64_t n,
    const int64_t k, const double alpha, const double *A, const int64_t lda,
    const int64_t strideA, const double *B, const int64_t ldb,
    const int64_t strideB, const double beta, double *C, const int64_t ldc,
    const int64_t strideC, const int64_t batch_count) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->dgemm_batch) {
    return;
  }

  const double **A_array =
      (const double **)fb_construct_strided_ptr_array(A, strideA, batch_count);
  const double **B_array =
      (const double **)fb_construct_strided_ptr_array(B, strideB, batch_count);
  double **C_array =
      (double **)fb_construct_strided_ptr_array(C, strideC, batch_count);

  if (!A_array || !B_array || !C_array) {
    fb_free_temp_buffer(A_array);
    fb_free_temp_buffer(B_array);
    fb_free_temp_buffer(C_array);
    return;
  }

  vtable->dgemm_batch(layout, transa, transb, m, n, k, alpha, A_array, lda,
                      B_array, ldb, beta, C_array, ldc, batch_count);

  fb_free_temp_buffer(A_array);
  fb_free_temp_buffer(B_array);
  fb_free_temp_buffer(C_array);
}

/* ============================================================================
 * GEMM: Strided Batched from Array Batched (CGEMM)
 * ========================================================================= */

void fb_cgemm_batch_strided_from_cgemm_batch(
    const fb_layout_t layout, const fb_transpose_t transa,
    const fb_transpose_t transb, const int64_t m, const int64_t n,
    const int64_t k, const fb_complex_float_t alpha,
    const fb_complex_float_t *A, const int64_t lda, const int64_t strideA,
    const fb_complex_float_t *B, const int64_t ldb, const int64_t strideB,
    const fb_complex_float_t beta, fb_complex_float_t *C, const int64_t ldc,
    const int64_t strideC, const int64_t batch_count) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->cgemm_batch) {
    return;
  }

  const fb_complex_float_t **A_array =
      (const fb_complex_float_t **)fb_construct_strided_ptr_array(A, strideA,
                                                                  batch_count);
  const fb_complex_float_t **B_array =
      (const fb_complex_float_t **)fb_construct_strided_ptr_array(B, strideB,
                                                                  batch_count);
  fb_complex_float_t **C_array =
      (fb_complex_float_t **)fb_construct_strided_ptr_array(C, strideC,
                                                            batch_count);

  if (!A_array || !B_array || !C_array) {
    fb_free_temp_buffer(A_array);
    fb_free_temp_buffer(B_array);
    fb_free_temp_buffer(C_array);
    return;
  }

  vtable->cgemm_batch(layout, transa, transb, m, n, k, alpha, A_array, lda,
                      B_array, ldb, beta, C_array, ldc, batch_count);

  fb_free_temp_buffer(A_array);
  fb_free_temp_buffer(B_array);
  fb_free_temp_buffer(C_array);
}

/* ============================================================================
 * GEMM: Strided Batched from Array Batched (ZGEMM)
 * ========================================================================= */

void fb_zgemm_batch_strided_from_zgemm_batch(
    const fb_layout_t layout, const fb_transpose_t transa,
    const fb_transpose_t transb, const int64_t m, const int64_t n,
    const int64_t k, const fb_complex_double_t alpha,
    const fb_complex_double_t *A, const int64_t lda, const int64_t strideA,
    const fb_complex_double_t *B, const int64_t ldb, const int64_t strideB,
    const fb_complex_double_t beta, fb_complex_double_t *C, const int64_t ldc,
    const int64_t strideC, const int64_t batch_count) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->zgemm_batch) {
    return;
  }

  const fb_complex_double_t **A_array =
      (const fb_complex_double_t **)fb_construct_strided_ptr_array(A, strideA,
                                                                   batch_count);
  const fb_complex_double_t **B_array =
      (const fb_complex_double_t **)fb_construct_strided_ptr_array(B, strideB,
                                                                   batch_count);
  fb_complex_double_t **C_array =
      (fb_complex_double_t **)fb_construct_strided_ptr_array(C, strideC,
                                                             batch_count);

  if (!A_array || !B_array || !C_array) {
    fb_free_temp_buffer(A_array);
    fb_free_temp_buffer(B_array);
    fb_free_temp_buffer(C_array);
    return;
  }

  vtable->zgemm_batch(layout, transa, transb, m, n, k, alpha, A_array, lda,
                      B_array, ldb, beta, C_array, ldc, batch_count);

  fb_free_temp_buffer(A_array);
  fb_free_temp_buffer(B_array);
  fb_free_temp_buffer(C_array);
}

/* ============================================================================
 * GEMV: Strided Batched from Array Batched (SGEMV)
 * ========================================================================= */

void fb_sgemv_batch_strided_from_sgemv_batch(
    const fb_layout_t layout, const fb_transpose_t trans, const int64_t m,
    const int64_t n, const float alpha, const float *A, const int64_t lda,
    const int64_t strideA, const float *x, const int64_t incx,
    const int64_t stridex, const float beta, float *y, const int64_t incy,
    const int64_t stridey, const int64_t batch_count) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->sgemv_batch) {
    return;
  }

  const float **A_array =
      (const float **)fb_construct_strided_ptr_array(A, strideA, batch_count);
  const float **x_array =
      (const float **)fb_construct_strided_ptr_array(x, stridex, batch_count);
  float **y_array =
      (float **)fb_construct_strided_ptr_array(y, stridey, batch_count);

  if (!A_array || !x_array || !y_array) {
    fb_free_temp_buffer(A_array);
    fb_free_temp_buffer(x_array);
    fb_free_temp_buffer(y_array);
    return;
  }

  vtable->sgemv_batch(layout, trans, m, n, alpha, A_array, lda, x_array, incx,
                      beta, y_array, incy, batch_count);

  fb_free_temp_buffer(A_array);
  fb_free_temp_buffer(x_array);
  fb_free_temp_buffer(y_array);
}

/* ============================================================================
 * GEMV: Strided Batched from Array Batched (DGEMV)
 * ========================================================================= */

void fb_dgemv_batch_strided_from_dgemv_batch(
    const fb_layout_t layout, const fb_transpose_t trans, const int64_t m,
    const int64_t n, const double alpha, const double *A, const int64_t lda,
    const int64_t strideA, const double *x, const int64_t incx,
    const int64_t stridex, const double beta, double *y, const int64_t incy,
    const int64_t stridey, const int64_t batch_count) {

  const fb_backend_vtable_t *vtable = fb_get_active_vtable();
  if (!vtable || !vtable->dgemv_batch) {
    return;
  }

  const double **A_array =
      (const double **)fb_construct_strided_ptr_array(A, strideA, batch_count);
  const double **x_array =
      (const double **)fb_construct_strided_ptr_array(x, stridex, batch_count);
  double **y_array =
      (double **)fb_construct_strided_ptr_array(y, stridey, batch_count);

  if (!A_array || !x_array || !y_array) {
    fb_free_temp_buffer(A_array);
    fb_free_temp_buffer(x_array);
    fb_free_temp_buffer(y_array);
    return;
  }

  vtable->dgemv_batch(layout, trans, m, n, alpha, A_array, lda, x_array, incx,
                      beta, y_array, incy, batch_count);

  fb_free_temp_buffer(A_array);
  fb_free_temp_buffer(x_array);
  fb_free_temp_buffer(y_array);
}

/* ============================================================================
 * Installer Functions
 * ========================================================================= */

/**
 * @brief Install strided batched GEMM wrappers from array-based variants
 *
 * @param vtable Vtable to fill
 */
void fb_autofill_gemm_batch_strided_from_gemm_batch(
    fb_backend_vtable_t *vtable) {
  if (!vtable) {
    return;
  }

  if (vtable->sgemm_batch_strided == NULL && vtable->sgemm_batch != NULL) {
    vtable->sgemm_batch_strided = fb_sgemm_batch_strided_from_sgemm_batch;
  }

  if (vtable->dgemm_batch_strided == NULL && vtable->dgemm_batch != NULL) {
    vtable->dgemm_batch_strided = fb_dgemm_batch_strided_from_dgemm_batch;
  }

  if (vtable->cgemm_batch_strided == NULL && vtable->cgemm_batch != NULL) {
    vtable->cgemm_batch_strided = fb_cgemm_batch_strided_from_cgemm_batch;
  }

  if (vtable->zgemm_batch_strided == NULL && vtable->zgemm_batch != NULL) {
    vtable->zgemm_batch_strided = fb_zgemm_batch_strided_from_zgemm_batch;
  }
}

/**
 * @brief Install strided batched GEMV wrappers from array-based variants
 *
 * @param vtable Vtable to fill
 */
void fb_autofill_gemv_batch_strided_from_gemv_batch(
    fb_backend_vtable_t *vtable) {
  if (!vtable) {
    return;
  }

  if (vtable->sgemv_batch_strided == NULL && vtable->sgemv_batch != NULL) {
    vtable->sgemv_batch_strided = fb_sgemv_batch_strided_from_sgemv_batch;
  }

  if (vtable->dgemv_batch_strided == NULL && vtable->dgemv_batch != NULL) {
    vtable->dgemv_batch_strided = fb_dgemv_batch_strided_from_dgemv_batch;
  }
}

/**
 * @brief Master installer for strided → array batched operations
 *
 * Called by fb_autofill_array_to_strided() in Strategy 3.
 *
 * @param vtable Vtable to fill
 */
void fb_autofill_all_strided_from_array(fb_backend_vtable_t *vtable) {
  if (!vtable) {
    return;
  }

  fb_autofill_gemm_batch_strided_from_gemm_batch(vtable);
  fb_autofill_gemv_batch_strided_from_gemv_batch(vtable);

  /* TODO: Phase 4.1 - Add more BLAS L1, L2 operations */
  /* TODO: Phase 4.2 - Add normalization strided → array */
  /* TODO: Phase 4.3 - Add reduction strided → array */
}
